=begin
#Interactions API

#Interactions API documentation

The version of the OpenAPI document: v1
Contact: api@demexchange.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

module DdxInteractionsApi
  VERSION = '0.1.0'
end
