# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.exchange_interaction_status import ExchangeInteractionStatus

class TestExchangeInteractionStatus(unittest.TestCase):
    """ExchangeInteractionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExchangeInteractionStatus(self):
        """Test ExchangeInteractionStatus"""
        # inst = ExchangeInteractionStatus()

if __name__ == '__main__':
    unittest.main()
