# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.api.authentication_details_api import AuthenticationDetailsApi


class TestAuthenticationDetailsApi(unittest.TestCase):
    """AuthenticationDetailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationDetailsApi()

    def tearDown(self) -> None:
        pass

    def test_vversion_auth_me_get(self) -> None:
        """Test case for vversion_auth_me_get

        Get authentication context
        """
        pass


if __name__ == '__main__':
    unittest.main()
