# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.person_identifier import PersonIdentifier

class TestPersonIdentifier(unittest.TestCase):
    """PersonIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PersonIdentifier:
        """Test PersonIdentifier
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PersonIdentifier`
        """
        model = PersonIdentifier()
        if include_optional:
            return PersonIdentifier(
                id = '0',
                type = '0'
            )
        else:
            return PersonIdentifier(
                id = '0',
                type = '0',
        )
        """

    def testPersonIdentifier(self):
        """Test PersonIdentifier"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
