# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.external_api_transaction_log_dto import ExternalApiTransactionLogDto

class TestExternalApiTransactionLogDto(unittest.TestCase):
    """ExternalApiTransactionLogDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalApiTransactionLogDto:
        """Test ExternalApiTransactionLogDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalApiTransactionLogDto`
        """
        model = ExternalApiTransactionLogDto()
        if include_optional:
            return ExternalApiTransactionLogDto(
                response_status_code = 56,
                response = '',
                date_created_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ExternalApiTransactionLogDto(
        )
        """

    def testExternalApiTransactionLogDto(self):
        """Test ExternalApiTransactionLogDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
