# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.van_api_key_dto import VanApiKeyDto

class TestVanApiKeyDto(unittest.TestCase):
    """VanApiKeyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VanApiKeyDto:
        """Test VanApiKeyDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VanApiKeyDto`
        """
        model = VanApiKeyDto()
        if include_optional:
            return VanApiKeyDto(
                external_api_key_id = 56,
                type = 'Van',
                status = 'Unknown',
                name = '',
                date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                connections = 56,
                committee_name = '',
                has_my_voters = True,
                has_my_campaign = True,
                key_ref = ''
            )
        else:
            return VanApiKeyDto(
        )
        """

    def testVanApiKeyDto(self):
        """Test VanApiKeyDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
