# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.contact_info import ContactInfo

class TestContactInfo(unittest.TestCase):
    """ContactInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactInfo:
        """Test ContactInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactInfo`
        """
        model = ContactInfo()
        if include_optional:
            return ContactInfo(
                email = [
                    ''
                    ],
                phone = [
                    ''
                    ],
                address = [
                    mi_interactions_api.models.address.Address(
                        address_line1 = '', 
                        address_line2 = '', 
                        city = '', 
                        state = '', 
                        postal_code = '', )
                    ],
                first_name = '',
                middle_name = '',
                last_name = '',
                social_handle = [
                    ''
                    ]
            )
        else:
            return ContactInfo(
        )
        """

    def testContactInfo(self):
        """Test ContactInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
