# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.exchange_interaction_status_dto import ExchangeInteractionStatusDto

class TestExchangeInteractionStatusDto(unittest.TestCase):
    """ExchangeInteractionStatusDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExchangeInteractionStatusDto:
        """Test ExchangeInteractionStatusDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExchangeInteractionStatusDto`
        """
        model = ExchangeInteractionStatusDto()
        if include_optional:
            return ExchangeInteractionStatusDto(
                correlation_id = '',
                interaction_id = '',
                status = 'Queued',
                publish_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ExchangeInteractionStatusDto(
        )
        """

    def testExchangeInteractionStatusDto(self):
        """Test ExchangeInteractionStatusDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
