# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.outcome import Outcome

class TestOutcome(unittest.TestCase):
    """Outcome unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutcome(self):
        """Test Outcome"""
        # inst = Outcome()

if __name__ == '__main__':
    unittest.main()
