# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.interaction_dto_channel import InteractionDtoChannel

class TestInteractionDtoChannel(unittest.TestCase):
    """InteractionDtoChannel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InteractionDtoChannel:
        """Test InteractionDtoChannel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InteractionDtoChannel`
        """
        model = InteractionDtoChannel()
        if include_optional:
            return InteractionDtoChannel(
                type = '',
                value = mi_interactions_api.models.value.value(),
                id = ''
            )
        else:
            return InteractionDtoChannel(
                type = '',
                value = mi_interactions_api.models.value.value(),
        )
        """

    def testInteractionDtoChannel(self):
        """Test InteractionDtoChannel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
