# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.who_am_i_api_key_dto import WhoAmIApiKeyDto

class TestWhoAmIApiKeyDto(unittest.TestCase):
    """WhoAmIApiKeyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WhoAmIApiKeyDto:
        """Test WhoAmIApiKeyDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WhoAmIApiKeyDto`
        """
        model = WhoAmIApiKeyDto()
        if include_optional:
            return WhoAmIApiKeyDto(
                public_key_id = 56,
                source = mi_interactions_api.models.simple_movement_app_dto.SimpleMovementAppDto(
                    movement_app_id = '', 
                    name = '', ),
                workspace = mi_interactions_api.models.workspace.Workspace(
                    workspace_id = 56, 
                    display_name = '', 
                    type = 'Personal', ),
                expire_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                destinations = [
                    mi_interactions_api.models.destination.Destination(
                        id = 56, 
                        name = '', 
                        is_van_destination = True, )
                    ],
                van_api_key = mi_interactions_api.models.mercury_destination_van_api_key_dto.MercuryDestinationVanApiKeyDto(
                    van_api_key_profile_details = mi_interactions_api.models.van_api_key_dto.VanApiKeyDto(
                        external_api_key_id = 56, 
                        type = 'Van', 
                        status = 'Unknown', 
                        name = '', 
                        date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        connections = 56, 
                        committee_name = '', 
                        has_my_voters = True, 
                        has_my_campaign = True, 
                        key_ref = '', ), 
                    selected_db_mode_access = 'MyVoters', )
            )
        else:
            return WhoAmIApiKeyDto(
                public_key_id = 56,
                source = mi_interactions_api.models.simple_movement_app_dto.SimpleMovementAppDto(
                    movement_app_id = '', 
                    name = '', ),
                workspace = mi_interactions_api.models.workspace.Workspace(
                    workspace_id = 56, 
                    display_name = '', 
                    type = 'Personal', ),
        )
        """

    def testWhoAmIApiKeyDto(self):
        """Test WhoAmIApiKeyDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
