# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.communication_consent_outcome_details import CommunicationConsentOutcomeDetails

class TestCommunicationConsentOutcomeDetails(unittest.TestCase):
    """CommunicationConsentOutcomeDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunicationConsentOutcomeDetails:
        """Test CommunicationConsentOutcomeDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunicationConsentOutcomeDetails`
        """
        model = CommunicationConsentOutcomeDetails()
        if include_optional:
            return CommunicationConsentOutcomeDetails(
                type = '',
                value = mi_interactions_api.models.communication_consent_outcome.Communication Consent Outcome(
                    consent_status = 'opted_in', )
            )
        else:
            return CommunicationConsentOutcomeDetails(
                value = mi_interactions_api.models.communication_consent_outcome.Communication Consent Outcome(
                    consent_status = 'opted_in', ),
        )
        """

    def testCommunicationConsentOutcomeDetails(self):
        """Test CommunicationConsentOutcomeDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
