# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.initiative_dto import InitiativeDto

class TestInitiativeDto(unittest.TestCase):
    """InitiativeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InitiativeDto:
        """Test InitiativeDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InitiativeDto`
        """
        model = InitiativeDto()
        if include_optional:
            return InitiativeDto(
                type = '',
                id = ''
            )
        else:
            return InitiativeDto(
        )
        """

    def testInitiativeDto(self):
        """Test InitiativeDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
