# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.interactions_dto import InteractionsDto

class TestInteractionsDto(unittest.TestCase):
    """InteractionsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InteractionsDto:
        """Test InteractionsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InteractionsDto`
        """
        model = InteractionsDto()
        if include_optional:
            return InteractionsDto(
                interactions = [
                    mi_interactions_api.models.interaction_dto.InteractionDto(
                        interaction_id = '', 
                        person = [
                            mi_interactions_api.models.person_identifier.PersonIdentifier(
                                id = '0', 
                                type = '0', )
                            ], 
                        contact_info = mi_interactions_api.models.contact_info.ContactInfo(
                            email = [
                                ''
                                ], 
                            phone = [
                                ''
                                ], 
                            address = [
                                mi_interactions_api.models.address.Address(
                                    address_line1 = '', 
                                    address_line2 = '', 
                                    city = '', 
                                    state = '', 
                                    postal_code = '', )
                                ], 
                            first_name = '', 
                            middle_name = '', 
                            last_name = '', 
                            social_handle = [
                                ''
                                ], ), 
                        channel = mi_interactions_api.models.interaction_dto_channel.InteractionDto_channel(
                            type = '', 
                            value = mi_interactions_api.models.value.value(), ), 
                        state_code = '01', 
                        attempt_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        method = 'unknown', 
                        committee = [
                            mi_interactions_api.models.committee_details.CommitteeDetails(
                                type = '0', 
                                id = '0', )
                            ], 
                        canvasser = [
                            mi_interactions_api.models.canvasser_details.CanvasserDetails(
                                type = '0', 
                                id = '0', )
                            ], 
                        vendor_source = '0', 
                        outcome = 'unknown', 
                        outcomes_detailed = [
                            mi_interactions_api.models.interaction_dto_outcomes_detailed_inner.InteractionDto_outcomesDetailed_inner(
                                type = '', 
                                value = mi_interactions_api.models.value.value(), )
                            ], 
                        thread_id = '', 
                        json_metadata = '', 
                        van_fields = mi_interactions_api.models.interaction_van_fields_dto.InteractionVanFieldsDto(
                            contact_type_id = '', 
                            result_code_id = '', ), 
                        initiative = [
                            mi_interactions_api.models.initiative_dto.InitiativeDto(
                                type = '', 
                                id = '', )
                            ], )
                    ]
            )
        else:
            return InteractionsDto(
        )
        """

    def testInteractionsDto(self):
        """Test InteractionsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
