# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.communication_consent_status import CommunicationConsentStatus

class TestCommunicationConsentStatus(unittest.TestCase):
    """CommunicationConsentStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommunicationConsentStatus(self):
        """Test CommunicationConsentStatus"""
        # inst = CommunicationConsentStatus()

if __name__ == '__main__':
    unittest.main()
