# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.dynamic_channel_details import DynamicChannelDetails

class TestDynamicChannelDetails(unittest.TestCase):
    """DynamicChannelDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DynamicChannelDetails:
        """Test DynamicChannelDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DynamicChannelDetails`
        """
        model = DynamicChannelDetails()
        if include_optional:
            return DynamicChannelDetails(
                id = '',
                type = '',
                value = None
            )
        else:
            return DynamicChannelDetails(
        )
        """

    def testDynamicChannelDetails(self):
        """Test DynamicChannelDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
