# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.exchange_interaction_status_dto_cursor_paginated_response_dto import ExchangeInteractionStatusDtoCursorPaginatedResponseDto

class TestExchangeInteractionStatusDtoCursorPaginatedResponseDto(unittest.TestCase):
    """ExchangeInteractionStatusDtoCursorPaginatedResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExchangeInteractionStatusDtoCursorPaginatedResponseDto:
        """Test ExchangeInteractionStatusDtoCursorPaginatedResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExchangeInteractionStatusDtoCursorPaginatedResponseDto`
        """
        model = ExchangeInteractionStatusDtoCursorPaginatedResponseDto()
        if include_optional:
            return ExchangeInteractionStatusDtoCursorPaginatedResponseDto(
                metadata = mi_interactions_api.models.minerva_metadata_dto.MinervaMetadataDto(
                    count = 56, ),
                data = [
                    mi_interactions_api.models.exchange_interaction_status_dto.ExchangeInteractionStatusDto(
                        correlation_id = '', 
                        interaction_id = '', 
                        status = 'Queued', 
                        publish_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_cursor = ''
            )
        else:
            return ExchangeInteractionStatusDtoCursorPaginatedResponseDto(
        )
        """

    def testExchangeInteractionStatusDtoCursorPaginatedResponseDto(self):
        """Test ExchangeInteractionStatusDtoCursorPaginatedResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
