# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.communication_consent import CommunicationConsent

class TestCommunicationConsent(unittest.TestCase):
    """CommunicationConsent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunicationConsent:
        """Test CommunicationConsent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunicationConsent`
        """
        model = CommunicationConsent()
        if include_optional:
            return CommunicationConsent(
                consent_status = 'opted_in'
            )
        else:
            return CommunicationConsent(
                consent_status = 'opted_in',
        )
        """

    def testCommunicationConsent(self):
        """Test CommunicationConsent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
