# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.external_api_transaction_dto_get_response_dto import ExternalApiTransactionDtoGetResponseDto

class TestExternalApiTransactionDtoGetResponseDto(unittest.TestCase):
    """ExternalApiTransactionDtoGetResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalApiTransactionDtoGetResponseDto:
        """Test ExternalApiTransactionDtoGetResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalApiTransactionDtoGetResponseDto`
        """
        model = ExternalApiTransactionDtoGetResponseDto()
        if include_optional:
            return ExternalApiTransactionDtoGetResponseDto(
                metadata = mi_interactions_api.models.minerva_metadata_dto.MinervaMetadataDto(
                    count = 56, ),
                data = [
                    mi_interactions_api.models.external_api_transaction_dto.ExternalApiTransactionDto(
                        date_created_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        interaction_id = '', 
                        correlation_id = '', 
                        status = 'Received', 
                        logs = [
                            mi_interactions_api.models.external_api_transaction_log_dto.ExternalApiTransactionLogDto(
                                response_status_code = 56, 
                                response = '', 
                                date_created_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], )
                    ]
            )
        else:
            return ExternalApiTransactionDtoGetResponseDto(
        )
        """

    def testExternalApiTransactionDtoGetResponseDto(self):
        """Test ExternalApiTransactionDtoGetResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
