# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mi_interactions_api.models.external_transaction_status import ExternalTransactionStatus

class TestExternalTransactionStatus(unittest.TestCase):
    """ExternalTransactionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalTransactionStatus(self):
        """Test ExternalTransactionStatus"""
        # inst = ExternalTransactionStatus()

if __name__ == '__main__':
    unittest.main()
