# -*- encoding: utf-8 -*-

=begin
#Interactions API

#Interactions API documentation

The version of the OpenAPI document: v1
Contact: api@demexchange.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "ddx_interactions_api/version"

Gem::Specification.new do |s|
  s.name        = "ddx_interactions_api"
  s.version     = DdxInteractionsApi::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["DDx API Team"]
  s.email       = ["mig-eng-inbox@demexchange.com"]
  s.homepage    = "https://github.com/Movement-Infrastructure/interactions-api-sdks"
  s.summary     = "Ruby client for the DDx Interactions API"
  s.description = "Ruby client for the DDx Interactions API, generated from the OpenAPI spec."
  s.license     = "MIT"
  s.required_ruby_version = ">= 3.0"
  s.metadata    = {}

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'
  s.add_runtime_dependency 'marcel'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  # Ship the library and its README only. The generator globs the whole
  # directory, which would publish docs/, spec/, the Gemfile, the Rakefile
  # and the generator config inside the gem.
  s.files         = Dir["lib/**/*"].select { |f| File.file?(f) } + ["README.md"]
  s.test_files    = []
  s.executables   = []
  s.require_paths = ["lib"]
end
