# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Outcome(str, Enum):
    """
    Outcome
    """

    """
    allowed enum values
    """
    UNKNOWN = 'unknown'
    CLICKED_LINK = 'clicked_link'
    EMAIL_OPENED = 'email_opened'
    SUBMITTED_FORM = 'submitted_form'
    SUCCESSFUL_CONTACT = 'successful_contact'
    DECEASED = 'deceased'
    DELIVERABILITY_ERROR = 'deliverability_error'
    PERMANENTLY_UNDELIVERABLE = 'permanently_undeliverable'
    INACCESSIBLE = 'inaccessible'
    LANGUAGE_BARRIER = 'language_barrier'
    MOVED = 'moved'
    NO_ANSWER = 'no_answer'
    WRONG_NUMBER = 'wrong_number'
    HOSTILE = 'hostile'
    MARKED_SPAM = 'marked_spam'
    REFUSED = 'refused'
    DELIVERED = 'delivered'
    LIT_DROP = 'lit_drop'
    LEFT_MESSAGE = 'left_message'
    OTHER = 'other'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Outcome from a JSON string"""
        return cls(json.loads(json_str))


