# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from mi_interactions_api.models.external_api_key_status import ExternalApiKeyStatus
from mi_interactions_api.models.external_api_key_type import ExternalApiKeyType
from typing import Optional, Set
from typing_extensions import Self

class VanApiKeyDto(BaseModel):
    """
    VAN-specific external key fields, for display and other front-end use
    """ # noqa: E501
    external_api_key_id: Optional[StrictInt] = Field(default=None, alias="externalApiKeyId")
    type: Optional[ExternalApiKeyType] = None
    status: Optional[ExternalApiKeyStatus] = None
    name: Optional[StrictStr] = None
    date_created: Optional[datetime] = Field(default=None, alias="dateCreated")
    connections: Optional[StrictInt] = None
    committee_name: Optional[StrictStr] = Field(default=None, alias="committeeName")
    has_my_voters: Optional[StrictBool] = Field(default=None, alias="hasMyVoters")
    has_my_campaign: Optional[StrictBool] = Field(default=None, alias="hasMyCampaign")
    key_ref: Optional[StrictStr] = Field(default=None, alias="keyRef")
    __properties: ClassVar[List[str]] = ["externalApiKeyId", "type", "status", "name", "dateCreated", "connections", "committeeName", "hasMyVoters", "hasMyCampaign", "keyRef"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VanApiKeyDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VanApiKeyDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "externalApiKeyId": obj.get("externalApiKeyId"),
            "type": obj.get("type"),
            "status": obj.get("status"),
            "name": obj.get("name"),
            "dateCreated": obj.get("dateCreated"),
            "connections": obj.get("connections"),
            "committeeName": obj.get("committeeName"),
            "hasMyVoters": obj.get("hasMyVoters"),
            "hasMyCampaign": obj.get("hasMyCampaign"),
            "keyRef": obj.get("keyRef")
        })
        return _obj


