# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class VanDatabaseMode(str, Enum):
    """
    VanDatabaseMode
    """

    """
    allowed enum values
    """
    MYVOTERS = 'MyVoters'
    MYCAMPAIGN = 'MyCampaign'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VanDatabaseMode from a JSON string"""
        return cls(json.loads(json_str))


