# coding: utf-8

"""
    Interactions API

    Interactions API documentation [test marker: MIG-1916 sync trigger]

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from mi_interactions_api.models.mercury_destination_van_api_key_dto import MercuryDestinationVanApiKeyDto
from mi_interactions_api.models.simple_destination_dto import SimpleDestinationDto
from mi_interactions_api.models.simple_movement_app_dto import SimpleMovementAppDto
from mi_interactions_api.models.simple_workspace_dto import SimpleWorkspaceDto
from typing import Optional, Set
from typing_extensions import Self

class WhoAmIApiKeyDto(BaseModel):
    """
    WhoAmIApiKeyDto
    """ # noqa: E501
    public_key_id: StrictInt = Field(description="Unique identifier that specifies which API Key is being used", alias="publicKeyId")
    source: SimpleMovementAppDto
    workspace: SimpleWorkspaceDto
    expire_date: Optional[datetime] = Field(default=None, description="The date and time the API Key is set to expire. The time should be evaluated in Eastern Time.", alias="expireDate")
    destinations: Optional[List[SimpleDestinationDto]] = Field(default=None, description="The destinations enabled for this API key")
    van_api_key: Optional[MercuryDestinationVanApiKeyDto] = Field(default=None, alias="vanApiKey")
    __properties: ClassVar[List[str]] = ["publicKeyId", "source", "workspace", "expireDate", "destinations", "vanApiKey"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WhoAmIApiKeyDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of workspace
        if self.workspace:
            _dict['workspace'] = self.workspace.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in destinations (list)
        _items = []
        if self.destinations:
            for _item_destinations in self.destinations:
                if _item_destinations:
                    _items.append(_item_destinations.to_dict())
            _dict['destinations'] = _items
        # override the default output from pydantic by calling `to_dict()` of van_api_key
        if self.van_api_key:
            _dict['vanApiKey'] = self.van_api_key.to_dict()
        # set to None if expire_date (nullable) is None
        # and model_fields_set contains the field
        if self.expire_date is None and "expire_date" in self.model_fields_set:
            _dict['expireDate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WhoAmIApiKeyDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "publicKeyId": obj.get("publicKeyId"),
            "source": SimpleMovementAppDto.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "workspace": SimpleWorkspaceDto.from_dict(obj["workspace"]) if obj.get("workspace") is not None else None,
            "expireDate": obj.get("expireDate"),
            "destinations": [SimpleDestinationDto.from_dict(_item) for _item in obj["destinations"]] if obj.get("destinations") is not None else None,
            "vanApiKey": MercuryDestinationVanApiKeyDto.from_dict(obj["vanApiKey"]) if obj.get("vanApiKey") is not None else None
        })
        return _obj


