/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Represents a collection of accepted interactions along with their count.
    /// </summary>
    [DataContract(Name = "AcceptedInteractionsDto")]
    public partial class AcceptedInteractionsDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AcceptedInteractionsDto" /> class.
        /// </summary>
        /// <param name="count">The total number of accepted interactions..</param>
        /// <param name="data">The list of accepted interactions..</param>
        public AcceptedInteractionsDto(int count = default(int), List<AcceptedInteractionDto> data = default(List<AcceptedInteractionDto>))
        {
            this.Count = count;
            this.Data = data;
        }

        /// <summary>
        /// The total number of accepted interactions.
        /// </summary>
        /// <value>The total number of accepted interactions.</value>
        [DataMember(Name = "count", EmitDefaultValue = false)]
        public int Count { get; set; }

        /// <summary>
        /// The list of accepted interactions.
        /// </summary>
        /// <value>The list of accepted interactions.</value>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public List<AcceptedInteractionDto> Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AcceptedInteractionsDto {\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
