/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// ActivistCode
    /// </summary>
    [DataContract(Name = "ActivistCode")]
    public partial class ActivistCode : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivistCode" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ActivistCode() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivistCode" /> class.
        /// </summary>
        /// <param name="activistCodeId">Unique identifier for an activist code;  the value may be retrieved from the system that sourced the activist code.</param>
        /// <param name="text">The question or information prompted during the interaction (required).</param>
        public ActivistCode(string activistCodeId = default(string), string text = default(string))
        {
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new ArgumentNullException("text is a required property for ActivistCode and cannot be null");
            }
            this.Text = text;
            this.ActivistCodeId = activistCodeId;
        }

        /// <summary>
        /// Unique identifier for an activist code;  the value may be retrieved from the system that sourced the activist code
        /// </summary>
        /// <value>Unique identifier for an activist code;  the value may be retrieved from the system that sourced the activist code</value>
        [DataMember(Name = "activistCodeId", EmitDefaultValue = true)]
        public string ActivistCodeId { get; set; }

        /// <summary>
        /// The question or information prompted during the interaction
        /// </summary>
        /// <value>The question or information prompted during the interaction</value>
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        public string Text { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActivistCode {\n");
            sb.Append("  ActivistCodeId: ").Append(ActivistCodeId).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Text (string) minLength
            if (this.Text != null && this.Text.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Text, length must be greater than 1.", new [] { "Text" });
            }

            yield break;
        }
    }

}
