/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Represents that an address was used for an interaction.
    /// </summary>
    [DataContract(Name = "AddressChannelDetails")]
    public partial class AddressChannelDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddressChannelDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddressChannelDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddressChannelDetails" /> class.
        /// </summary>
        /// <param name="id">Optional; unique identifier for any known id for the channel &#x60;type&#x60;.</param>
        /// <param name="type">Specifies that the &#x60;type&#x60; of channel used was an &#x60;address&#x60; and a full address must be provided as the &#x60;value&#x60;. (required).</param>
        /// <param name="value">value (required).</param>
        public AddressChannelDetails(string id = default(string), string type = default(string), Address value = default(Address))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for AddressChannelDetails and cannot be null");
            }
            this.Type = type;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for AddressChannelDetails and cannot be null");
            }
            this.Value = value;
            this.Id = id;
        }

        /// <summary>
        /// Optional; unique identifier for any known id for the channel &#x60;type&#x60;
        /// </summary>
        /// <value>Optional; unique identifier for any known id for the channel &#x60;type&#x60;</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Specifies that the &#x60;type&#x60; of channel used was an &#x60;address&#x60; and a full address must be provided as the &#x60;value&#x60;.
        /// </summary>
        /// <value>Specifies that the &#x60;type&#x60; of channel used was an &#x60;address&#x60; and a full address must be provided as the &#x60;value&#x60;.</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public Address Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddressChannelDetails {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Type (string) minLength
            if (this.Type != null && this.Type.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Type, length must be greater than 1.", new [] { "Type" });
            }

            yield break;
        }
    }

}
