/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// CommunicationConsent
    /// </summary>
    [DataContract(Name = "CommunicationConsent")]
    public partial class CommunicationConsent : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets ConsentStatus
        /// </summary>
        [DataMember(Name = "consentStatus", IsRequired = true, EmitDefaultValue = true)]
        public CommunicationConsentStatus ConsentStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CommunicationConsent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CommunicationConsent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CommunicationConsent" /> class.
        /// </summary>
        /// <param name="consentStatus">consentStatus (required).</param>
        public CommunicationConsent(CommunicationConsentStatus consentStatus = default(CommunicationConsentStatus))
        {
            this.ConsentStatus = consentStatus;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CommunicationConsent {\n");
            sb.Append("  ConsentStatus: ").Append(ConsentStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
