/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Defines ContactMethod
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ContactMethod
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown,

        /// <summary>
        /// Enum Mail for value: mail
        /// </summary>
        [EnumMember(Value = "mail")]
        Mail,

        /// <summary>
        /// Enum Letter for value: letter
        /// </summary>
        [EnumMember(Value = "letter")]
        Letter,

        /// <summary>
        /// Enum DigitalAd for value: digital_ad
        /// </summary>
        [EnumMember(Value = "digital_ad")]
        DigitalAd,

        /// <summary>
        /// Enum Email for value: email
        /// </summary>
        [EnumMember(Value = "email")]
        Email,

        /// <summary>
        /// Enum Text for value: text
        /// </summary>
        [EnumMember(Value = "text")]
        Text,

        /// <summary>
        /// Enum TextBroadcast for value: text_broadcast
        /// </summary>
        [EnumMember(Value = "text_broadcast")]
        TextBroadcast,

        /// <summary>
        /// Enum RoboCall for value: robo_call
        /// </summary>
        [EnumMember(Value = "robo_call")]
        RoboCall,

        /// <summary>
        /// Enum DialerCall for value: dialer_call
        /// </summary>
        [EnumMember(Value = "dialer_call")]
        DialerCall,

        /// <summary>
        /// Enum PhoneCall for value: phone_call
        /// </summary>
        [EnumMember(Value = "phone_call")]
        PhoneCall,

        /// <summary>
        /// Enum DoorKnock for value: door_knock
        /// </summary>
        [EnumMember(Value = "door_knock")]
        DoorKnock,

        /// <summary>
        /// Enum Event for value: Event
        /// </summary>
        [EnumMember(Value = "Event")]
        Event,

        /// <summary>
        /// Enum HotSpot for value: hot_spot
        /// </summary>
        [EnumMember(Value = "hot_spot")]
        HotSpot,

        /// <summary>
        /// Enum OneOnOne for value: one_on_one
        /// </summary>
        [EnumMember(Value = "one_on_one")]
        OneOnOne,

        /// <summary>
        /// Enum WebInteraction for value: web_interaction
        /// </summary>
        [EnumMember(Value = "web_interaction")]
        WebInteraction
    }

}
