/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Represents contact information for a person being interacted with, including email, phone, or address.  Can be used to match a person if an Id is not known
    /// </summary>
    [DataContract(Name = "ContactInfo")]
    public partial class ContactInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContactInfo" /> class.
        /// </summary>
        /// <param name="email">Email addresses of the person being interacted with..</param>
        /// <param name="phone">Phone numbers of the person being interacted with. Should be in E.164 format (e.g. +1234567890)..</param>
        /// <param name="address">Physical addresses of the person being interacted with..</param>
        /// <param name="firstName">Optional first name field for person being interacted with..</param>
        /// <param name="middleName">Optional middle name field for person being interacted with..</param>
        /// <param name="lastName">Optional last name field for person being interacted with..</param>
        /// <param name="socialHandle">Optional social media handles for person being interacted with..</param>
        public ContactInfo(List<string> email = default(List<string>), List<string> phone = default(List<string>), List<Address> address = default(List<Address>), string firstName = default(string), string middleName = default(string), string lastName = default(string), List<string> socialHandle = default(List<string>))
        {
            this.Email = email;
            this.Phone = phone;
            this.Address = address;
            this.FirstName = firstName;
            this.MiddleName = middleName;
            this.LastName = lastName;
            this.SocialHandle = socialHandle;
        }

        /// <summary>
        /// Email addresses of the person being interacted with.
        /// </summary>
        /// <value>Email addresses of the person being interacted with.</value>
        [DataMember(Name = "email", EmitDefaultValue = true)]
        public List<string> Email { get; set; }

        /// <summary>
        /// Phone numbers of the person being interacted with. Should be in E.164 format (e.g. +1234567890).
        /// </summary>
        /// <value>Phone numbers of the person being interacted with. Should be in E.164 format (e.g. +1234567890).</value>
        [DataMember(Name = "phone", EmitDefaultValue = true)]
        public List<string> Phone { get; set; }

        /// <summary>
        /// Physical addresses of the person being interacted with.
        /// </summary>
        /// <value>Physical addresses of the person being interacted with.</value>
        [DataMember(Name = "address", EmitDefaultValue = true)]
        public List<Address> Address { get; set; }

        /// <summary>
        /// Optional first name field for person being interacted with.
        /// </summary>
        /// <value>Optional first name field for person being interacted with.</value>
        [DataMember(Name = "firstName", EmitDefaultValue = true)]
        public string FirstName { get; set; }

        /// <summary>
        /// Optional middle name field for person being interacted with.
        /// </summary>
        /// <value>Optional middle name field for person being interacted with.</value>
        [DataMember(Name = "middleName", EmitDefaultValue = true)]
        public string MiddleName { get; set; }

        /// <summary>
        /// Optional last name field for person being interacted with.
        /// </summary>
        /// <value>Optional last name field for person being interacted with.</value>
        [DataMember(Name = "lastName", EmitDefaultValue = true)]
        public string LastName { get; set; }

        /// <summary>
        /// Optional social media handles for person being interacted with.
        /// </summary>
        /// <value>Optional social media handles for person being interacted with.</value>
        [DataMember(Name = "socialHandle", EmitDefaultValue = true)]
        public List<string> SocialHandle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContactInfo {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  MiddleName: ").Append(MiddleName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  SocialHandle: ").Append(SocialHandle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
