/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Represents a generic Outcome Details object;  does not have any validation rules or JSON format limitations
    /// </summary>
    [DataContract(Name = "DynamicOutcomeDetails")]
    public partial class DynamicOutcomeDetails : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Operation
        /// </summary>
        [DataMember(Name = "operation", EmitDefaultValue = false)]
        public OutcomeDetailOperation? Operation { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DynamicOutcomeDetails" /> class.
        /// </summary>
        /// <param name="operation">operation.</param>
        /// <param name="type">This field categorizes the type of detailed outcome information being provided..</param>
        /// <param name="value"> Provide additional details of the outreach attempt. This field can be provided as a string or int though only the object form is shown here..</param>
        public DynamicOutcomeDetails(OutcomeDetailOperation? operation = default(OutcomeDetailOperation?), string type = default(string), Object value = default(Object))
        {
            this.Operation = operation;
            this.Type = type;
            this.Value = value;
        }

        /// <summary>
        /// This field categorizes the type of detailed outcome information being provided.
        /// </summary>
        /// <value>This field categorizes the type of detailed outcome information being provided.</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        ///  Provide additional details of the outreach attempt. This field can be provided as a string or int though only the object form is shown here.
        /// </summary>
        /// <value> Provide additional details of the outreach attempt. This field can be provided as a string or int though only the object form is shown here.</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public Object Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DynamicOutcomeDetails {\n");
            sb.Append("  Operation: ").Append(Operation).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
