/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Represents a generic Channel Details object;  does not have any validation rules or JSON format limitations except where noted below.
    /// </summary>
    [DataContract(Name = "DynamicChannelDetails")]
    public partial class DynamicChannelDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DynamicChannelDetails" /> class.
        /// </summary>
        /// <param name="id">Optional; unique identifier for any known id for the channel &#x60;type&#x60;.</param>
        /// <param name="type">Type of the channel specified in &#39;value&#39;. Required when Channel is provided.                Recognized types:  - \&quot;phone_number\&quot;: Indicates &#x60;value&#x60; is a phone number; &#x60;value&#x60; must be in E.164 format (e.g., +14155552671).  - \&quot;email\&quot;: Indicates &#x60;value&#x60; is an email address.  - [any other identifier]: Any type not listed above. &#x60;value&#x60; can be a string, an int or an arbitrary object..</param>
        /// <param name="value"> The actual channel used during the outreach attempt. This field can be provided as a string or int though only the object form is shown here.   Examples: +14155552671, name@org.org, @handle.   Required when Channel is provided..</param>
        public DynamicChannelDetails(string id = default(string), string type = default(string), Object value = default(Object))
        {
            this.Id = id;
            this.Type = type;
            this.Value = value;
        }

        /// <summary>
        /// Optional; unique identifier for any known id for the channel &#x60;type&#x60;
        /// </summary>
        /// <value>Optional; unique identifier for any known id for the channel &#x60;type&#x60;</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Type of the channel specified in &#39;value&#39;. Required when Channel is provided.                Recognized types:  - \&quot;phone_number\&quot;: Indicates &#x60;value&#x60; is a phone number; &#x60;value&#x60; must be in E.164 format (e.g., +14155552671).  - \&quot;email\&quot;: Indicates &#x60;value&#x60; is an email address.  - [any other identifier]: Any type not listed above. &#x60;value&#x60; can be a string, an int or an arbitrary object.
        /// </summary>
        /// <value>Type of the channel specified in &#39;value&#39;. Required when Channel is provided.                Recognized types:  - \&quot;phone_number\&quot;: Indicates &#x60;value&#x60; is a phone number; &#x60;value&#x60; must be in E.164 format (e.g., +14155552671).  - \&quot;email\&quot;: Indicates &#x60;value&#x60; is an email address.  - [any other identifier]: Any type not listed above. &#x60;value&#x60; can be a string, an int or an arbitrary object.</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        ///  The actual channel used during the outreach attempt. This field can be provided as a string or int though only the object form is shown here.   Examples: +14155552671, name@org.org, @handle.   Required when Channel is provided.
        /// </summary>
        /// <value> The actual channel used during the outreach attempt. This field can be provided as a string or int though only the object form is shown here.   Examples: +14155552671, name@org.org, @handle.   Required when Channel is provided.</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public Object Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DynamicChannelDetails {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
