/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Represents the status of an event signup
    /// </summary>
    [DataContract(Name = "EventSignupStatus")]
    public partial class EventSignupStatus : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public EventSignupStatusValue Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventSignupStatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventSignupStatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventSignupStatus" /> class.
        /// </summary>
        /// <param name="status">status (required).</param>
        /// <param name="vendorReference">Open string field for vendor-specific reference information.</param>
        public EventSignupStatus(EventSignupStatusValue status = default(EventSignupStatusValue), string vendorReference = default(string))
        {
            this.Status = status;
            this.VendorReference = vendorReference;
        }

        /// <summary>
        /// Open string field for vendor-specific reference information
        /// </summary>
        /// <value>Open string field for vendor-specific reference information</value>
        [DataMember(Name = "vendor_reference", EmitDefaultValue = true)]
        public string VendorReference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventSignupStatus {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  VendorReference: ").Append(VendorReference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
