/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Represents an event signup captured during an interaction.
    /// </summary>
    [DataContract(Name = "EventSignup")]
    public partial class EventSignup : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventSignup" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventSignup() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventSignup" /> class.
        /// </summary>
        /// <param name="eventId">eventId (required).</param>
        /// <param name="shifts">Optional array of shift identifiers for specific shifts within the event.</param>
        /// <param name="role">role.</param>
        /// <param name="status">status.</param>
        public EventSignup(EventDetails eventId = default(EventDetails), List<EventDetails> shifts = default(List<EventDetails>), EventRole role = default(EventRole), EventSignupStatus status = default(EventSignupStatus))
        {
            // to ensure "eventId" is required (not null)
            if (eventId == null)
            {
                throw new ArgumentNullException("eventId is a required property for EventSignup and cannot be null");
            }
            this.EventId = eventId;
            this.Shifts = shifts;
            this.Role = role;
            this.Status = status;
        }

        /// <summary>
        /// Gets or Sets EventId
        /// </summary>
        [DataMember(Name = "event_id", IsRequired = true, EmitDefaultValue = true)]
        public EventDetails EventId { get; set; }

        /// <summary>
        /// Optional array of shift identifiers for specific shifts within the event
        /// </summary>
        /// <value>Optional array of shift identifiers for specific shifts within the event</value>
        [DataMember(Name = "shifts", EmitDefaultValue = true)]
        public List<EventDetails> Shifts { get; set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [DataMember(Name = "role", EmitDefaultValue = false)]
        public EventRole Role { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public EventSignupStatus Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventSignup {\n");
            sb.Append("  EventId: ").Append(EventId).Append("\n");
            sb.Append("  Shifts: ").Append(Shifts).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
