/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Extends Minerva.Dto.Api.GetResponseDto&#x60;1 with cursor-based pagination support.
    /// </summary>
    [DataContract(Name = "ExchangeInteractionStatusDtoCursorPaginatedResponseDto")]
    public partial class ExchangeInteractionStatusDtoCursorPaginatedResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExchangeInteractionStatusDtoCursorPaginatedResponseDto" /> class.
        /// </summary>
        /// <param name="metadata">metadata.</param>
        /// <param name="data">data.</param>
        /// <param name="nextCursor">Opaque cursor token for fetching the next page. Null if there are no more results..</param>
        public ExchangeInteractionStatusDtoCursorPaginatedResponseDto(MinervaMetadataDto metadata = default(MinervaMetadataDto), List<ExchangeInteractionStatusDto> data = default(List<ExchangeInteractionStatusDto>), string nextCursor = default(string))
        {
            this.Metadata = metadata;
            this.Data = data;
            this.NextCursor = nextCursor;
        }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public MinervaMetadataDto Metadata { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public List<ExchangeInteractionStatusDto> Data { get; set; }

        /// <summary>
        /// Opaque cursor token for fetching the next page. Null if there are no more results.
        /// </summary>
        /// <value>Opaque cursor token for fetching the next page. Null if there are no more results.</value>
        [DataMember(Name = "nextCursor", EmitDefaultValue = true)]
        public string NextCursor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExchangeInteractionStatusDtoCursorPaginatedResponseDto {\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  NextCursor: ").Append(NextCursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
