/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Defines ExternalTransactionStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ExternalTransactionStatus
    {
        /// <summary>
        /// Enum Received for value: Received
        /// </summary>
        [EnumMember(Value = "Received")]
        Received = 1,

        /// <summary>
        /// Enum Processing for value: Processing
        /// </summary>
        [EnumMember(Value = "Processing")]
        Processing = 2,

        /// <summary>
        /// Enum Success for value: Success
        /// </summary>
        [EnumMember(Value = "Success")]
        Success = 3,

        /// <summary>
        /// Enum Failed for value: Failed
        /// </summary>
        [EnumMember(Value = "Failed")]
        Failed = 4,

        /// <summary>
        /// Enum Invalid for value: Invalid
        /// </summary>
        [EnumMember(Value = "Invalid")]
        Invalid = 5,

        /// <summary>
        /// Enum Duplicate for value: Duplicate
        /// </summary>
        [EnumMember(Value = "Duplicate")]
        Duplicate = 6,

        /// <summary>
        /// Enum InternalError for value: InternalError
        /// </summary>
        [EnumMember(Value = "InternalError")]
        InternalError = 7
    }

}
