/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Log data for an external API transaction to a configured Interactions API destination.
    /// </summary>
    [DataContract(Name = "InteractionsExternalApiTransactionLogDto")]
    public partial class InteractionsExternalApiTransactionLogDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionsExternalApiTransactionLogDto" /> class.
        /// </summary>
        /// <param name="responseStatusCode">HTTP response code received for external API request..</param>
        /// <param name="response">Response JSON received for external API request..</param>
        /// <param name="dateCreatedUtc">Timestamp for when the external API request was made..</param>
        public InteractionsExternalApiTransactionLogDto(int? responseStatusCode = default(int?), string response = default(string), DateTime dateCreatedUtc = default(DateTime))
        {
            this.ResponseStatusCode = responseStatusCode;
            this.Response = response;
            this.DateCreatedUtc = dateCreatedUtc;
        }

        /// <summary>
        /// HTTP response code received for external API request.
        /// </summary>
        /// <value>HTTP response code received for external API request.</value>
        [DataMember(Name = "responseStatusCode", EmitDefaultValue = true)]
        public int? ResponseStatusCode { get; set; }

        /// <summary>
        /// Response JSON received for external API request.
        /// </summary>
        /// <value>Response JSON received for external API request.</value>
        [DataMember(Name = "response", EmitDefaultValue = true)]
        public string Response { get; set; }

        /// <summary>
        /// Timestamp for when the external API request was made.
        /// </summary>
        /// <value>Timestamp for when the external API request was made.</value>
        [DataMember(Name = "dateCreatedUtc", EmitDefaultValue = false)]
        public DateTime DateCreatedUtc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InteractionsExternalApiTransactionLogDto {\n");
            sb.Append("  ResponseStatusCode: ").Append(ResponseStatusCode).Append("\n");
            sb.Append("  Response: ").Append(Response).Append("\n");
            sb.Append("  DateCreatedUtc: ").Append(DateCreatedUtc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
