/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// InteractionDtoOutcomesDetailedInner
    /// </summary>
    [JsonConverter(typeof(InteractionDtoOutcomesDetailedInnerJsonConverter))]
    [DataContract(Name = "InteractionDto_outcomesDetailed_inner")]
    public partial class InteractionDtoOutcomesDetailedInner : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionDtoOutcomesDetailedInner" /> class
        /// with the <see cref="ActivistCodeOutcomeDetails" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ActivistCodeOutcomeDetails.</param>
        public InteractionDtoOutcomesDetailedInner(ActivistCodeOutcomeDetails actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionDtoOutcomesDetailedInner" /> class
        /// with the <see cref="SurveyResponseOutcomeDetails" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SurveyResponseOutcomeDetails.</param>
        public InteractionDtoOutcomesDetailedInner(SurveyResponseOutcomeDetails actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionDtoOutcomesDetailedInner" /> class
        /// with the <see cref="CommunicationConsentOutcomeDetails" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CommunicationConsentOutcomeDetails.</param>
        public InteractionDtoOutcomesDetailedInner(CommunicationConsentOutcomeDetails actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionDtoOutcomesDetailedInner" /> class
        /// with the <see cref="EventSignupOutcomeDetails" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of EventSignupOutcomeDetails.</param>
        public InteractionDtoOutcomesDetailedInner(EventSignupOutcomeDetails actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionDtoOutcomesDetailedInner" /> class
        /// with the <see cref="DynamicOutcomeDetails" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of DynamicOutcomeDetails.</param>
        public InteractionDtoOutcomesDetailedInner(DynamicOutcomeDetails actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ActivistCodeOutcomeDetails) || value is ActivistCodeOutcomeDetails)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(CommunicationConsentOutcomeDetails) || value is CommunicationConsentOutcomeDetails)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(DynamicOutcomeDetails) || value is DynamicOutcomeDetails)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(EventSignupOutcomeDetails) || value is EventSignupOutcomeDetails)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SurveyResponseOutcomeDetails) || value is SurveyResponseOutcomeDetails)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ActivistCodeOutcomeDetails, CommunicationConsentOutcomeDetails, DynamicOutcomeDetails, EventSignupOutcomeDetails, SurveyResponseOutcomeDetails");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `ActivistCodeOutcomeDetails`. If the actual instance is not `ActivistCodeOutcomeDetails`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ActivistCodeOutcomeDetails</returns>
        public ActivistCodeOutcomeDetails GetActivistCodeOutcomeDetails()
        {
            return (ActivistCodeOutcomeDetails)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SurveyResponseOutcomeDetails`. If the actual instance is not `SurveyResponseOutcomeDetails`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SurveyResponseOutcomeDetails</returns>
        public SurveyResponseOutcomeDetails GetSurveyResponseOutcomeDetails()
        {
            return (SurveyResponseOutcomeDetails)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `CommunicationConsentOutcomeDetails`. If the actual instance is not `CommunicationConsentOutcomeDetails`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CommunicationConsentOutcomeDetails</returns>
        public CommunicationConsentOutcomeDetails GetCommunicationConsentOutcomeDetails()
        {
            return (CommunicationConsentOutcomeDetails)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `EventSignupOutcomeDetails`. If the actual instance is not `EventSignupOutcomeDetails`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of EventSignupOutcomeDetails</returns>
        public EventSignupOutcomeDetails GetEventSignupOutcomeDetails()
        {
            return (EventSignupOutcomeDetails)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `DynamicOutcomeDetails`. If the actual instance is not `DynamicOutcomeDetails`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of DynamicOutcomeDetails</returns>
        public DynamicOutcomeDetails GetDynamicOutcomeDetails()
        {
            return (DynamicOutcomeDetails)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InteractionDtoOutcomesDetailedInner {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, InteractionDtoOutcomesDetailedInner.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of InteractionDtoOutcomesDetailedInner
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of InteractionDtoOutcomesDetailedInner</returns>
        public static InteractionDtoOutcomesDetailedInner FromJson(string jsonString)
        {
            InteractionDtoOutcomesDetailedInner newInteractionDtoOutcomesDetailedInner = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newInteractionDtoOutcomesDetailedInner;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ActivistCodeOutcomeDetails).GetProperty("AdditionalProperties") == null)
                {
                    newInteractionDtoOutcomesDetailedInner = new InteractionDtoOutcomesDetailedInner(JsonConvert.DeserializeObject<ActivistCodeOutcomeDetails>(jsonString, InteractionDtoOutcomesDetailedInner.SerializerSettings));
                }
                else
                {
                    newInteractionDtoOutcomesDetailedInner = new InteractionDtoOutcomesDetailedInner(JsonConvert.DeserializeObject<ActivistCodeOutcomeDetails>(jsonString, InteractionDtoOutcomesDetailedInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ActivistCodeOutcomeDetails");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ActivistCodeOutcomeDetails: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(CommunicationConsentOutcomeDetails).GetProperty("AdditionalProperties") == null)
                {
                    newInteractionDtoOutcomesDetailedInner = new InteractionDtoOutcomesDetailedInner(JsonConvert.DeserializeObject<CommunicationConsentOutcomeDetails>(jsonString, InteractionDtoOutcomesDetailedInner.SerializerSettings));
                }
                else
                {
                    newInteractionDtoOutcomesDetailedInner = new InteractionDtoOutcomesDetailedInner(JsonConvert.DeserializeObject<CommunicationConsentOutcomeDetails>(jsonString, InteractionDtoOutcomesDetailedInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("CommunicationConsentOutcomeDetails");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CommunicationConsentOutcomeDetails: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(DynamicOutcomeDetails).GetProperty("AdditionalProperties") == null)
                {
                    newInteractionDtoOutcomesDetailedInner = new InteractionDtoOutcomesDetailedInner(JsonConvert.DeserializeObject<DynamicOutcomeDetails>(jsonString, InteractionDtoOutcomesDetailedInner.SerializerSettings));
                }
                else
                {
                    newInteractionDtoOutcomesDetailedInner = new InteractionDtoOutcomesDetailedInner(JsonConvert.DeserializeObject<DynamicOutcomeDetails>(jsonString, InteractionDtoOutcomesDetailedInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("DynamicOutcomeDetails");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into DynamicOutcomeDetails: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(EventSignupOutcomeDetails).GetProperty("AdditionalProperties") == null)
                {
                    newInteractionDtoOutcomesDetailedInner = new InteractionDtoOutcomesDetailedInner(JsonConvert.DeserializeObject<EventSignupOutcomeDetails>(jsonString, InteractionDtoOutcomesDetailedInner.SerializerSettings));
                }
                else
                {
                    newInteractionDtoOutcomesDetailedInner = new InteractionDtoOutcomesDetailedInner(JsonConvert.DeserializeObject<EventSignupOutcomeDetails>(jsonString, InteractionDtoOutcomesDetailedInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("EventSignupOutcomeDetails");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into EventSignupOutcomeDetails: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SurveyResponseOutcomeDetails).GetProperty("AdditionalProperties") == null)
                {
                    newInteractionDtoOutcomesDetailedInner = new InteractionDtoOutcomesDetailedInner(JsonConvert.DeserializeObject<SurveyResponseOutcomeDetails>(jsonString, InteractionDtoOutcomesDetailedInner.SerializerSettings));
                }
                else
                {
                    newInteractionDtoOutcomesDetailedInner = new InteractionDtoOutcomesDetailedInner(JsonConvert.DeserializeObject<SurveyResponseOutcomeDetails>(jsonString, InteractionDtoOutcomesDetailedInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SurveyResponseOutcomeDetails");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SurveyResponseOutcomeDetails: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newInteractionDtoOutcomesDetailedInner;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for InteractionDtoOutcomesDetailedInner
    /// </summary>
    public class InteractionDtoOutcomesDetailedInnerJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(InteractionDtoOutcomesDetailedInner).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return InteractionDtoOutcomesDetailedInner.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return InteractionDtoOutcomesDetailedInner.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
