/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// For an interaction request with an external destination configured, this represents the status of the interaction data sent to that destination.
    /// </summary>
    [DataContract(Name = "InteractionsExternalApiTransactionDto")]
    public partial class InteractionsExternalApiTransactionDto : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public ExternalTransactionStatus? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionsExternalApiTransactionDto" /> class.
        /// </summary>
        /// <param name="dateCreatedUtc">The UTC date and time at which the request was received..</param>
        /// <param name="interactionId">ID used to identify the interaction; ID will have been returned from the initial publish response..</param>
        /// <param name="correlationId">DDx API request identifier, provided as X-Correlation-Id on interactions responses for use linking all interactions in a request..</param>
        /// <param name="status">status.</param>
        /// <param name="logs">Any logs associated with this external API transaction..</param>
        public InteractionsExternalApiTransactionDto(DateTime dateCreatedUtc = default(DateTime), Guid interactionId = default(Guid), string correlationId = default(string), ExternalTransactionStatus? status = default(ExternalTransactionStatus?), List<InteractionsExternalApiTransactionLogDto> logs = default(List<InteractionsExternalApiTransactionLogDto>))
        {
            this.DateCreatedUtc = dateCreatedUtc;
            this.InteractionId = interactionId;
            this.CorrelationId = correlationId;
            this.Status = status;
            this.Logs = logs;
        }

        /// <summary>
        /// The UTC date and time at which the request was received.
        /// </summary>
        /// <value>The UTC date and time at which the request was received.</value>
        [DataMember(Name = "dateCreatedUtc", EmitDefaultValue = false)]
        public DateTime DateCreatedUtc { get; set; }

        /// <summary>
        /// ID used to identify the interaction; ID will have been returned from the initial publish response.
        /// </summary>
        /// <value>ID used to identify the interaction; ID will have been returned from the initial publish response.</value>
        [DataMember(Name = "interactionId", EmitDefaultValue = false)]
        public Guid InteractionId { get; set; }

        /// <summary>
        /// DDx API request identifier, provided as X-Correlation-Id on interactions responses for use linking all interactions in a request.
        /// </summary>
        /// <value>DDx API request identifier, provided as X-Correlation-Id on interactions responses for use linking all interactions in a request.</value>
        [DataMember(Name = "correlationId", EmitDefaultValue = false)]
        public string CorrelationId { get; set; }

        /// <summary>
        /// Any logs associated with this external API transaction.
        /// </summary>
        /// <value>Any logs associated with this external API transaction.</value>
        [DataMember(Name = "logs", EmitDefaultValue = false)]
        public List<InteractionsExternalApiTransactionLogDto> Logs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InteractionsExternalApiTransactionDto {\n");
            sb.Append("  DateCreatedUtc: ").Append(DateCreatedUtc).Append("\n");
            sb.Append("  InteractionId: ").Append(InteractionId).Append("\n");
            sb.Append("  CorrelationId: ").Append(CorrelationId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Logs: ").Append(Logs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
