/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Channel-of-contact details used during the outreach attempt.  If the &#x60;type&#x60; is recognized as an Address Channel (type &#x3D; \&quot;address\&quot;), the &#x60;value&#x60; will be deserialized to that object type.  Other string-based types have specific validation documented in the \&quot;Channel\&quot; section below, like \&quot;phone_number\&quot;.  If the &#x60;type&#x60; is unrecognized, the payload will be deserialized to an unvalidated, loosely typed object for flexibility.
    /// </summary>
    [JsonConverter(typeof(InteractionDtoChannelJsonConverter))]
    [DataContract(Name = "InteractionDto_channel")]
    public partial class InteractionDtoChannel : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionDtoChannel" /> class.
        /// </summary>
        public InteractionDtoChannel()
        {
            this.IsNullable = true;
            this.SchemaType= "oneOf";
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionDtoChannel" /> class
        /// with the <see cref="AddressChannelDetails" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of AddressChannelDetails.</param>
        public InteractionDtoChannel(AddressChannelDetails actualInstance)
        {
            this.IsNullable = true;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionDtoChannel" /> class
        /// with the <see cref="DynamicChannelDetails" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of DynamicChannelDetails.</param>
        public InteractionDtoChannel(DynamicChannelDetails actualInstance)
        {
            this.IsNullable = true;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(AddressChannelDetails) || value is AddressChannelDetails)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(DynamicChannelDetails) || value is DynamicChannelDetails)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: AddressChannelDetails, DynamicChannelDetails");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `AddressChannelDetails`. If the actual instance is not `AddressChannelDetails`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of AddressChannelDetails</returns>
        public AddressChannelDetails GetAddressChannelDetails()
        {
            return (AddressChannelDetails)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `DynamicChannelDetails`. If the actual instance is not `DynamicChannelDetails`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of DynamicChannelDetails</returns>
        public DynamicChannelDetails GetDynamicChannelDetails()
        {
            return (DynamicChannelDetails)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InteractionDtoChannel {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, InteractionDtoChannel.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of InteractionDtoChannel
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of InteractionDtoChannel</returns>
        public static InteractionDtoChannel FromJson(string jsonString)
        {
            InteractionDtoChannel newInteractionDtoChannel = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newInteractionDtoChannel;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(AddressChannelDetails).GetProperty("AdditionalProperties") == null)
                {
                    newInteractionDtoChannel = new InteractionDtoChannel(JsonConvert.DeserializeObject<AddressChannelDetails>(jsonString, InteractionDtoChannel.SerializerSettings));
                }
                else
                {
                    newInteractionDtoChannel = new InteractionDtoChannel(JsonConvert.DeserializeObject<AddressChannelDetails>(jsonString, InteractionDtoChannel.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("AddressChannelDetails");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into AddressChannelDetails: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(DynamicChannelDetails).GetProperty("AdditionalProperties") == null)
                {
                    newInteractionDtoChannel = new InteractionDtoChannel(JsonConvert.DeserializeObject<DynamicChannelDetails>(jsonString, InteractionDtoChannel.SerializerSettings));
                }
                else
                {
                    newInteractionDtoChannel = new InteractionDtoChannel(JsonConvert.DeserializeObject<DynamicChannelDetails>(jsonString, InteractionDtoChannel.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("DynamicChannelDetails");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into DynamicChannelDetails: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newInteractionDtoChannel;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for InteractionDtoChannel
    /// </summary>
    public class InteractionDtoChannelJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(InteractionDtoChannel).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return InteractionDtoChannel.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return InteractionDtoChannel.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
