/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Represents the result of processing a batch of interactions, including accepted and rejected interactions.
    /// </summary>
    [DataContract(Name = "InteractionsBatchResultDto")]
    public partial class InteractionsBatchResultDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionsBatchResultDto" /> class.
        /// </summary>
        /// <param name="correlationId">DDx API request identifier, provided as X-Correlation-Id on interactions responses for use linking all interactions in a request..</param>
        /// <param name="totalInteractions">Total number of interactions in the batch..</param>
        /// <param name="acceptedInteractions">acceptedInteractions.</param>
        /// <param name="rejectedInteractions">rejectedInteractions.</param>
        public InteractionsBatchResultDto(string correlationId = default(string), int totalInteractions = default(int), AcceptedInteractionsDto acceptedInteractions = default(AcceptedInteractionsDto), RejectedInteractionsDto rejectedInteractions = default(RejectedInteractionsDto))
        {
            this.CorrelationId = correlationId;
            this.TotalInteractions = totalInteractions;
            this.AcceptedInteractions = acceptedInteractions;
            this.RejectedInteractions = rejectedInteractions;
        }

        /// <summary>
        /// DDx API request identifier, provided as X-Correlation-Id on interactions responses for use linking all interactions in a request.
        /// </summary>
        /// <value>DDx API request identifier, provided as X-Correlation-Id on interactions responses for use linking all interactions in a request.</value>
        [DataMember(Name = "correlationId", EmitDefaultValue = false)]
        public string CorrelationId { get; set; }

        /// <summary>
        /// Total number of interactions in the batch.
        /// </summary>
        /// <value>Total number of interactions in the batch.</value>
        [DataMember(Name = "totalInteractions", EmitDefaultValue = false)]
        public int TotalInteractions { get; set; }

        /// <summary>
        /// Gets or Sets AcceptedInteractions
        /// </summary>
        [DataMember(Name = "acceptedInteractions", EmitDefaultValue = false)]
        public AcceptedInteractionsDto AcceptedInteractions { get; set; }

        /// <summary>
        /// Gets or Sets RejectedInteractions
        /// </summary>
        [DataMember(Name = "rejectedInteractions", EmitDefaultValue = false)]
        public RejectedInteractionsDto RejectedInteractions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InteractionsBatchResultDto {\n");
            sb.Append("  CorrelationId: ").Append(CorrelationId).Append("\n");
            sb.Append("  TotalInteractions: ").Append(TotalInteractions).Append("\n");
            sb.Append("  AcceptedInteractions: ").Append(AcceptedInteractions).Append("\n");
            sb.Append("  RejectedInteractions: ").Append(RejectedInteractions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
