/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// VAN-specific DTO containing VAN key profile details along with DDx configuration for that VAN key for the linked destination.
    /// </summary>
    [DataContract(Name = "MercuryDestinationVanApiKeyDto")]
    public partial class MercuryDestinationVanApiKeyDto : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets SelectedDbModeAccess
        /// </summary>
        [DataMember(Name = "selectedDbModeAccess", EmitDefaultValue = false)]
        public VanDatabaseMode? SelectedDbModeAccess { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MercuryDestinationVanApiKeyDto" /> class.
        /// </summary>
        /// <param name="vanApiKeyProfileDetails">vanApiKeyProfileDetails.</param>
        /// <param name="selectedDbModeAccess">selectedDbModeAccess.</param>
        public MercuryDestinationVanApiKeyDto(VanApiKeyDto vanApiKeyProfileDetails = default(VanApiKeyDto), VanDatabaseMode? selectedDbModeAccess = default(VanDatabaseMode?))
        {
            this.VanApiKeyProfileDetails = vanApiKeyProfileDetails;
            this.SelectedDbModeAccess = selectedDbModeAccess;
        }

        /// <summary>
        /// Gets or Sets VanApiKeyProfileDetails
        /// </summary>
        [DataMember(Name = "vanApiKeyProfileDetails", EmitDefaultValue = false)]
        public VanApiKeyDto VanApiKeyProfileDetails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MercuryDestinationVanApiKeyDto {\n");
            sb.Append("  VanApiKeyProfileDetails: ").Append(VanApiKeyProfileDetails).Append("\n");
            sb.Append("  SelectedDbModeAccess: ").Append(SelectedDbModeAccess).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
