/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Defines OutcomeDetailOperation
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OutcomeDetailOperation
    {
        /// <summary>
        /// Enum Create for value: create
        /// </summary>
        [EnumMember(Value = "create")]
        Create = 1,

        /// <summary>
        /// Enum Delete for value: delete
        /// </summary>
        [EnumMember(Value = "delete")]
        Delete = 2,

        /// <summary>
        /// Enum Update for value: update
        /// </summary>
        [EnumMember(Value = "update")]
        Update = 3
    }

}
