/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Defines Outcome
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Outcome
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown,

        /// <summary>
        /// Enum ClickedLink for value: clicked_link
        /// </summary>
        [EnumMember(Value = "clicked_link")]
        ClickedLink,

        /// <summary>
        /// Enum EmailOpened for value: email_opened
        /// </summary>
        [EnumMember(Value = "email_opened")]
        EmailOpened,

        /// <summary>
        /// Enum SubmittedForm for value: submitted_form
        /// </summary>
        [EnumMember(Value = "submitted_form")]
        SubmittedForm,

        /// <summary>
        /// Enum SuccessfulContact for value: successful_contact
        /// </summary>
        [EnumMember(Value = "successful_contact")]
        SuccessfulContact,

        /// <summary>
        /// Enum Deceased for value: deceased
        /// </summary>
        [EnumMember(Value = "deceased")]
        Deceased,

        /// <summary>
        /// Enum DeliverabilityError for value: deliverability_error
        /// </summary>
        [EnumMember(Value = "deliverability_error")]
        DeliverabilityError,

        /// <summary>
        /// Enum PermanentlyUndeliverable for value: permanently_undeliverable
        /// </summary>
        [EnumMember(Value = "permanently_undeliverable")]
        PermanentlyUndeliverable,

        /// <summary>
        /// Enum Inaccessible for value: inaccessible
        /// </summary>
        [EnumMember(Value = "inaccessible")]
        Inaccessible,

        /// <summary>
        /// Enum LanguageBarrier for value: language_barrier
        /// </summary>
        [EnumMember(Value = "language_barrier")]
        LanguageBarrier,

        /// <summary>
        /// Enum Moved for value: moved
        /// </summary>
        [EnumMember(Value = "moved")]
        Moved,

        /// <summary>
        /// Enum NoAnswer for value: no_answer
        /// </summary>
        [EnumMember(Value = "no_answer")]
        NoAnswer,

        /// <summary>
        /// Enum WrongNumber for value: wrong_number
        /// </summary>
        [EnumMember(Value = "wrong_number")]
        WrongNumber,

        /// <summary>
        /// Enum Hostile for value: hostile
        /// </summary>
        [EnumMember(Value = "hostile")]
        Hostile,

        /// <summary>
        /// Enum MarkedSpam for value: marked_spam
        /// </summary>
        [EnumMember(Value = "marked_spam")]
        MarkedSpam,

        /// <summary>
        /// Enum Refused for value: refused
        /// </summary>
        [EnumMember(Value = "refused")]
        Refused,

        /// <summary>
        /// Enum Delivered for value: delivered
        /// </summary>
        [EnumMember(Value = "delivered")]
        Delivered,

        /// <summary>
        /// Enum LitDrop for value: lit_drop
        /// </summary>
        [EnumMember(Value = "lit_drop")]
        LitDrop,

        /// <summary>
        /// Enum LeftMessage for value: left_message
        /// </summary>
        [EnumMember(Value = "left_message")]
        LeftMessage,

        /// <summary>
        /// Enum Other for value: other
        /// </summary>
        [EnumMember(Value = "other")]
        Other
    }

}
