/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// Represents a rejected interaction with its associated errors.
    /// </summary>
    [DataContract(Name = "RejectedInteractionDto")]
    public partial class RejectedInteractionDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RejectedInteractionDto" /> class.
        /// </summary>
        /// <param name="interactionId">ID used to identify the interaction; ID will have been returned from the initial publish response..</param>
        /// <param name="index">Index of the rejected interaction in the batch..</param>
        /// <param name="errors">List of errors associated with the rejected interaction..</param>
        public RejectedInteractionDto(Guid interactionId = default(Guid), int index = default(int), List<InteractionErrorDto> errors = default(List<InteractionErrorDto>))
        {
            this.InteractionId = interactionId;
            this.Index = index;
            this.Errors = errors;
        }

        /// <summary>
        /// ID used to identify the interaction; ID will have been returned from the initial publish response.
        /// </summary>
        /// <value>ID used to identify the interaction; ID will have been returned from the initial publish response.</value>
        [DataMember(Name = "interactionId", EmitDefaultValue = false)]
        public Guid InteractionId { get; set; }

        /// <summary>
        /// Index of the rejected interaction in the batch.
        /// </summary>
        /// <value>Index of the rejected interaction in the batch.</value>
        [DataMember(Name = "index", EmitDefaultValue = false)]
        public int Index { get; set; }

        /// <summary>
        /// List of errors associated with the rejected interaction.
        /// </summary>
        /// <value>List of errors associated with the rejected interaction.</value>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public List<InteractionErrorDto> Errors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RejectedInteractionDto {\n");
            sb.Append("  InteractionId: ").Append(InteractionId).Append("\n");
            sb.Append("  Index: ").Append(Index).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
