/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// SimpleDestinationDto
    /// </summary>
    [DataContract(Name = "SimpleDestinationDto")]
    public partial class SimpleDestinationDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SimpleDestinationDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SimpleDestinationDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SimpleDestinationDto" /> class.
        /// </summary>
        /// <param name="id">Unique identifier for the destination (required).</param>
        /// <param name="name">Display name for the destination.</param>
        /// <param name="isVanDestination">Indicator of whether the destination integrates with NGP VAN  and requires an associated VAN External API Key.</param>
        public SimpleDestinationDto(int id = default(int), string name = default(string), bool isVanDestination = default(bool))
        {
            this.Id = id;
            this.Name = name;
            this.IsVanDestination = isVanDestination;
        }

        /// <summary>
        /// Unique identifier for the destination
        /// </summary>
        /// <value>Unique identifier for the destination</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public int Id { get; set; }

        /// <summary>
        /// Display name for the destination
        /// </summary>
        /// <value>Display name for the destination</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Indicator of whether the destination integrates with NGP VAN  and requires an associated VAN External API Key
        /// </summary>
        /// <value>Indicator of whether the destination integrates with NGP VAN  and requires an associated VAN External API Key</value>
        [DataMember(Name = "isVanDestination", EmitDefaultValue = true)]
        public bool IsVanDestination { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SimpleDestinationDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IsVanDestination: ").Append(IsVanDestination).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
