/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// SurveyResponse
    /// </summary>
    [DataContract(Name = "SurveyResponse")]
    public partial class SurveyResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SurveyResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SurveyResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SurveyResponse" /> class.
        /// </summary>
        /// <param name="questionId">Unique identifier for the survey question being asked;  the value may be retrieved from the system that sourced the question.</param>
        /// <param name="questionText">The question text presented during an interaction (required).</param>
        /// <param name="responseId">Unique identifier for the survey response associated with the question;  the value may be retrieved from the system that sourced the question.</param>
        /// <param name="responseText">An answer to the question.  Required when Survey Question text is provided. (required).</param>
        public SurveyResponse(string questionId = default(string), string questionText = default(string), string responseId = default(string), string responseText = default(string))
        {
            // to ensure "questionText" is required (not null)
            if (questionText == null)
            {
                throw new ArgumentNullException("questionText is a required property for SurveyResponse and cannot be null");
            }
            this.QuestionText = questionText;
            // to ensure "responseText" is required (not null)
            if (responseText == null)
            {
                throw new ArgumentNullException("responseText is a required property for SurveyResponse and cannot be null");
            }
            this.ResponseText = responseText;
            this.QuestionId = questionId;
            this.ResponseId = responseId;
        }

        /// <summary>
        /// Unique identifier for the survey question being asked;  the value may be retrieved from the system that sourced the question
        /// </summary>
        /// <value>Unique identifier for the survey question being asked;  the value may be retrieved from the system that sourced the question</value>
        [DataMember(Name = "questionId", EmitDefaultValue = true)]
        public string QuestionId { get; set; }

        /// <summary>
        /// The question text presented during an interaction
        /// </summary>
        /// <value>The question text presented during an interaction</value>
        [DataMember(Name = "questionText", IsRequired = true, EmitDefaultValue = true)]
        public string QuestionText { get; set; }

        /// <summary>
        /// Unique identifier for the survey response associated with the question;  the value may be retrieved from the system that sourced the question
        /// </summary>
        /// <value>Unique identifier for the survey response associated with the question;  the value may be retrieved from the system that sourced the question</value>
        [DataMember(Name = "responseId", EmitDefaultValue = true)]
        public string ResponseId { get; set; }

        /// <summary>
        /// An answer to the question.  Required when Survey Question text is provided.
        /// </summary>
        /// <value>An answer to the question.  Required when Survey Question text is provided.</value>
        [DataMember(Name = "responseText", IsRequired = true, EmitDefaultValue = true)]
        public string ResponseText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SurveyResponse {\n");
            sb.Append("  QuestionId: ").Append(QuestionId).Append("\n");
            sb.Append("  QuestionText: ").Append(QuestionText).Append("\n");
            sb.Append("  ResponseId: ").Append(ResponseId).Append("\n");
            sb.Append("  ResponseText: ").Append(ResponseText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // QuestionText (string) minLength
            if (this.QuestionText != null && this.QuestionText.Length < 1)
            {
                yield return new ValidationResult("Invalid value for QuestionText, length must be greater than 1.", new [] { "QuestionText" });
            }

            // ResponseText (string) minLength
            if (this.ResponseText != null && this.ResponseText.Length < 1)
            {
                yield return new ValidationResult("Invalid value for ResponseText, length must be greater than 1.", new [] { "ResponseText" });
            }

            yield break;
        }
    }

}
