/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Ddx.InteractionsApi.Client.FileParameter;
using OpenAPIDateConverter = Ddx.InteractionsApi.Client.OpenAPIDateConverter;

namespace Ddx.InteractionsApi.Model
{
    /// <summary>
    /// VAN-specific external key fields, for display and other front-end use
    /// </summary>
    [DataContract(Name = "VanApiKeyDto")]
    public partial class VanApiKeyDto : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public ExternalApiKeyType? Type { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public ExternalApiKeyStatus? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VanApiKeyDto" /> class.
        /// </summary>
        /// <param name="externalApiKeyId">externalApiKeyId.</param>
        /// <param name="type">type.</param>
        /// <param name="status">status.</param>
        /// <param name="name">name.</param>
        /// <param name="dateCreated">dateCreated.</param>
        /// <param name="connections">connections.</param>
        /// <param name="committeeName">committeeName.</param>
        /// <param name="hasMyVoters">hasMyVoters.</param>
        /// <param name="hasMyCampaign">hasMyCampaign.</param>
        /// <param name="keyRef">keyRef.</param>
        public VanApiKeyDto(int externalApiKeyId = default(int), ExternalApiKeyType? type = default(ExternalApiKeyType?), ExternalApiKeyStatus? status = default(ExternalApiKeyStatus?), string name = default(string), DateTime dateCreated = default(DateTime), int connections = default(int), string committeeName = default(string), bool hasMyVoters = default(bool), bool hasMyCampaign = default(bool), string keyRef = default(string))
        {
            this.ExternalApiKeyId = externalApiKeyId;
            this.Type = type;
            this.Status = status;
            this.Name = name;
            this.DateCreated = dateCreated;
            this.Connections = connections;
            this.CommitteeName = committeeName;
            this.HasMyVoters = hasMyVoters;
            this.HasMyCampaign = hasMyCampaign;
            this.KeyRef = keyRef;
        }

        /// <summary>
        /// Gets or Sets ExternalApiKeyId
        /// </summary>
        [DataMember(Name = "externalApiKeyId", EmitDefaultValue = false)]
        public int ExternalApiKeyId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets DateCreated
        /// </summary>
        [DataMember(Name = "dateCreated", EmitDefaultValue = false)]
        public DateTime DateCreated { get; set; }

        /// <summary>
        /// Gets or Sets Connections
        /// </summary>
        [DataMember(Name = "connections", EmitDefaultValue = false)]
        public int Connections { get; set; }

        /// <summary>
        /// Gets or Sets CommitteeName
        /// </summary>
        [DataMember(Name = "committeeName", EmitDefaultValue = false)]
        public string CommitteeName { get; set; }

        /// <summary>
        /// Gets or Sets HasMyVoters
        /// </summary>
        [DataMember(Name = "hasMyVoters", EmitDefaultValue = true)]
        public bool HasMyVoters { get; set; }

        /// <summary>
        /// Gets or Sets HasMyCampaign
        /// </summary>
        [DataMember(Name = "hasMyCampaign", EmitDefaultValue = true)]
        public bool HasMyCampaign { get; set; }

        /// <summary>
        /// Gets or Sets KeyRef
        /// </summary>
        [DataMember(Name = "keyRef", EmitDefaultValue = false)]
        public string KeyRef { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VanApiKeyDto {\n");
            sb.Append("  ExternalApiKeyId: ").Append(ExternalApiKeyId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  DateCreated: ").Append(DateCreated).Append("\n");
            sb.Append("  Connections: ").Append(Connections).Append("\n");
            sb.Append("  CommitteeName: ").Append(CommitteeName).Append("\n");
            sb.Append("  HasMyVoters: ").Append(HasMyVoters).Append("\n");
            sb.Append("  HasMyCampaign: ").Append(HasMyCampaign).Append("\n");
            sb.Append("  KeyRef: ").Append(KeyRef).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
