/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents an accepted interaction with its associated index.
 * @export
 * @interface AcceptedInteractionDto
 */
export interface AcceptedInteractionDto {
    /**
     * ID used to identify the interaction; ID will have been returned from the initial publish response.
     * @type {string}
     * @memberof AcceptedInteractionDto
     */
    interactionId?: string;
    /**
     * Index of the accepted interaction in the batch.
     * @type {number}
     * @memberof AcceptedInteractionDto
     */
    index?: number;
}

/**
 * Check if a given object implements the AcceptedInteractionDto interface.
 */
export function instanceOfAcceptedInteractionDto(value: object): value is AcceptedInteractionDto {
    return true;
}

export function AcceptedInteractionDtoFromJSON(json: any): AcceptedInteractionDto {
    return AcceptedInteractionDtoFromJSONTyped(json, false);
}

export function AcceptedInteractionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptedInteractionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'interactionId': json['interactionId'] == null ? undefined : json['interactionId'],
        'index': json['index'] == null ? undefined : json['index'],
    };
}

export function AcceptedInteractionDtoToJSON(json: any): AcceptedInteractionDto {
    return AcceptedInteractionDtoToJSONTyped(json, false);
}

export function AcceptedInteractionDtoToJSONTyped(value?: AcceptedInteractionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interactionId': value['interactionId'],
        'index': value['index'],
    };
}

