/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivistCode } from './ActivistCode';
import {
    ActivistCodeFromJSON,
    ActivistCodeFromJSONTyped,
    ActivistCodeToJSON,
    ActivistCodeToJSONTyped,
} from './ActivistCode';

/**
 * Represents an activist code (e.g. affiliation, activity, or interest) acquired during an interaction.
 * @export
 * @interface ActivistCodeOutcomeDetails
 */
export interface ActivistCodeOutcomeDetails {
    /**
     * Describes whether this outcome detail is being created, deleted, or updated. Which operations are accepted varies by outcome type. Defaults to create.
     * @type {string}
     * @memberof ActivistCodeOutcomeDetails
     */
    operation?: ActivistCodeOutcomeDetailsOperationEnum;
    /**
     * This field categorizes the type of detailed outcome information being provided.
     * @type {string}
     * @memberof ActivistCodeOutcomeDetails
     */
    type?: string;
    /**
     * 
     * @type {ActivistCode}
     * @memberof ActivistCodeOutcomeDetails
     */
    value: ActivistCode;
}


/**
 * @export
 */
export const ActivistCodeOutcomeDetailsOperationEnum = {
    Create: 'create',
    Delete: 'delete'
} as const;
export type ActivistCodeOutcomeDetailsOperationEnum = typeof ActivistCodeOutcomeDetailsOperationEnum[keyof typeof ActivistCodeOutcomeDetailsOperationEnum];


/**
 * Check if a given object implements the ActivistCodeOutcomeDetails interface.
 */
export function instanceOfActivistCodeOutcomeDetails(value: object): value is ActivistCodeOutcomeDetails {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ActivistCodeOutcomeDetailsFromJSON(json: any): ActivistCodeOutcomeDetails {
    return ActivistCodeOutcomeDetailsFromJSONTyped(json, false);
}

export function ActivistCodeOutcomeDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivistCodeOutcomeDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['operation'] == null ? undefined : json['operation'],
        'type': json['type'] == null ? undefined : json['type'],
        'value': ActivistCodeFromJSON(json['value']),
    };
}

export function ActivistCodeOutcomeDetailsToJSON(json: any): ActivistCodeOutcomeDetails {
    return ActivistCodeOutcomeDetailsToJSONTyped(json, false);
}

export function ActivistCodeOutcomeDetailsToJSONTyped(value?: ActivistCodeOutcomeDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation': value['operation'],
        'type': value['type'],
        'value': ActivistCodeToJSON(value['value']),
    };
}

