/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * Represents that an address was used for an interaction.
 * @export
 * @interface AddressChannelDetails
 */
export interface AddressChannelDetails {
    /**
     * Optional; unique identifier for any known id for the channel `type`
     * @type {string}
     * @memberof AddressChannelDetails
     */
    id?: string | null;
    /**
     * Specifies that the `type` of channel used was an `address` and a full address must be provided as the `value`.
     * @type {string}
     * @memberof AddressChannelDetails
     */
    type: string;
    /**
     * 
     * @type {Address}
     * @memberof AddressChannelDetails
     */
    value: Address;
}

/**
 * Check if a given object implements the AddressChannelDetails interface.
 */
export function instanceOfAddressChannelDetails(value: object): value is AddressChannelDetails {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AddressChannelDetailsFromJSON(json: any): AddressChannelDetails {
    return AddressChannelDetailsFromJSONTyped(json, false);
}

export function AddressChannelDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressChannelDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'],
        'value': AddressFromJSON(json['value']),
    };
}

export function AddressChannelDetailsToJSON(json: any): AddressChannelDetails {
    return AddressChannelDetailsToJSONTyped(json, false);
}

export function AddressChannelDetailsToJSONTyped(value?: AddressChannelDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'value': AddressToJSON(value['value']),
    };
}

