/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents canvasser details for the individual who conducted the outreach attempt.
 * @export
 * @interface CanvasserDetails
 */
export interface CanvasserDetails {
    /**
     * Type of the canvasser identifier specified in 'id'.
     * Required when Canvasser is provided.
     * @type {string}
     * @memberof CanvasserDetails
     */
    type: string;
    /**
     * The actual canvasser identifier used during the outreach attempt.
     * Examples: user ID, employee number, volunteer ID, etc.
     * Required when Canvasser is provided.
     * @type {string}
     * @memberof CanvasserDetails
     */
    id: string;
}

/**
 * Check if a given object implements the CanvasserDetails interface.
 */
export function instanceOfCanvasserDetails(value: object): value is CanvasserDetails {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CanvasserDetailsFromJSON(json: any): CanvasserDetails {
    return CanvasserDetailsFromJSONTyped(json, false);
}

export function CanvasserDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CanvasserDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function CanvasserDetailsToJSON(json: any): CanvasserDetails {
    return CanvasserDetailsToJSONTyped(json, false);
}

export function CanvasserDetailsToJSONTyped(value?: CanvasserDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

