/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommunicationConsent } from './CommunicationConsent';
import {
    CommunicationConsentFromJSON,
    CommunicationConsentFromJSONTyped,
    CommunicationConsentToJSON,
    CommunicationConsentToJSONTyped,
} from './CommunicationConsent';

/**
 * Represents a communication consent response ("opted_in" or "opted_out").
 * @export
 * @interface CommunicationConsentOutcomeDetails
 */
export interface CommunicationConsentOutcomeDetails {
    /**
     * Describes whether this outcome detail is being created, deleted, or updated. Which operations are accepted varies by outcome type. Defaults to create.
     * @type {string}
     * @memberof CommunicationConsentOutcomeDetails
     */
    operation?: CommunicationConsentOutcomeDetailsOperationEnum;
    /**
     * This field categorizes the type of detailed outcome information being provided.
     * @type {string}
     * @memberof CommunicationConsentOutcomeDetails
     */
    type?: string;
    /**
     * 
     * @type {CommunicationConsent}
     * @memberof CommunicationConsentOutcomeDetails
     */
    value: CommunicationConsent;
}


/**
 * @export
 */
export const CommunicationConsentOutcomeDetailsOperationEnum = {
    Create: 'create',
    Delete: 'delete'
} as const;
export type CommunicationConsentOutcomeDetailsOperationEnum = typeof CommunicationConsentOutcomeDetailsOperationEnum[keyof typeof CommunicationConsentOutcomeDetailsOperationEnum];


/**
 * Check if a given object implements the CommunicationConsentOutcomeDetails interface.
 */
export function instanceOfCommunicationConsentOutcomeDetails(value: object): value is CommunicationConsentOutcomeDetails {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CommunicationConsentOutcomeDetailsFromJSON(json: any): CommunicationConsentOutcomeDetails {
    return CommunicationConsentOutcomeDetailsFromJSONTyped(json, false);
}

export function CommunicationConsentOutcomeDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunicationConsentOutcomeDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['operation'] == null ? undefined : json['operation'],
        'type': json['type'] == null ? undefined : json['type'],
        'value': CommunicationConsentFromJSON(json['value']),
    };
}

export function CommunicationConsentOutcomeDetailsToJSON(json: any): CommunicationConsentOutcomeDetails {
    return CommunicationConsentOutcomeDetailsToJSONTyped(json, false);
}

export function CommunicationConsentOutcomeDetailsToJSONTyped(value?: CommunicationConsentOutcomeDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation': value['operation'],
        'type': value['type'],
        'value': CommunicationConsentToJSON(value['value']),
    };
}

