/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommunicationConsentStatus } from './CommunicationConsentStatus';
import {
    CommunicationConsentStatusFromJSON,
    CommunicationConsentStatusFromJSONTyped,
    CommunicationConsentStatusToJSON,
    CommunicationConsentStatusToJSONTyped,
} from './CommunicationConsentStatus';

/**
 * 
 * @export
 * @interface CommunicationConsent
 */
export interface CommunicationConsent {
    /**
     * 
     * @type {CommunicationConsentStatus}
     * @memberof CommunicationConsent
     */
    consentStatus: CommunicationConsentStatus;
}



/**
 * Check if a given object implements the CommunicationConsent interface.
 */
export function instanceOfCommunicationConsent(value: object): value is CommunicationConsent {
    if (!('consentStatus' in value) || value['consentStatus'] === undefined) return false;
    return true;
}

export function CommunicationConsentFromJSON(json: any): CommunicationConsent {
    return CommunicationConsentFromJSONTyped(json, false);
}

export function CommunicationConsentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunicationConsent {
    if (json == null) {
        return json;
    }
    return {
        
        'consentStatus': CommunicationConsentStatusFromJSON(json['consentStatus']),
    };
}

export function CommunicationConsentToJSON(json: any): CommunicationConsent {
    return CommunicationConsentToJSONTyped(json, false);
}

export function CommunicationConsentToJSONTyped(value?: CommunicationConsent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'consentStatus': CommunicationConsentStatusToJSON(value['consentStatus']),
    };
}

