/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * Represents contact information for a person being interacted with, including email, phone, or address.
 * Can be used to match a person if an Id is not known
 * @export
 * @interface ContactInfo
 */
export interface ContactInfo {
    /**
     * Email addresses of the person being interacted with.
     * @type {Array<string>}
     * @memberof ContactInfo
     */
    email?: Array<string> | null;
    /**
     * Phone numbers of the person being interacted with. Should be in E.164 format (e.g. +1234567890).
     * @type {Array<string>}
     * @memberof ContactInfo
     */
    phone?: Array<string> | null;
    /**
     * Physical addresses of the person being interacted with.
     * @type {Array<Address>}
     * @memberof ContactInfo
     */
    address?: Array<Address> | null;
    /**
     * Optional first name field for person being interacted with.
     * @type {string}
     * @memberof ContactInfo
     */
    firstName?: string | null;
    /**
     * Optional middle name field for person being interacted with.
     * @type {string}
     * @memberof ContactInfo
     */
    middleName?: string | null;
    /**
     * Optional last name field for person being interacted with.
     * @type {string}
     * @memberof ContactInfo
     */
    lastName?: string | null;
    /**
     * Optional social media handles for person being interacted with.
     * @type {Array<string>}
     * @memberof ContactInfo
     */
    socialHandle?: Array<string> | null;
}

/**
 * Check if a given object implements the ContactInfo interface.
 */
export function instanceOfContactInfo(value: object): value is ContactInfo {
    return true;
}

export function ContactInfoFromJSON(json: any): ContactInfo {
    return ContactInfoFromJSONTyped(json, false);
}

export function ContactInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'address': json['address'] == null ? undefined : ((json['address'] as Array<any>).map(AddressFromJSON)),
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'middleName': json['middleName'] == null ? undefined : json['middleName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'socialHandle': json['socialHandle'] == null ? undefined : json['socialHandle'],
    };
}

export function ContactInfoToJSON(json: any): ContactInfo {
    return ContactInfoToJSONTyped(json, false);
}

export function ContactInfoToJSONTyped(value?: ContactInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'phone': value['phone'],
        'address': value['address'] == null ? undefined : ((value['address'] as Array<any>).map(AddressToJSON)),
        'firstName': value['firstName'],
        'middleName': value['middleName'],
        'lastName': value['lastName'],
        'socialHandle': value['socialHandle'],
    };
}

