/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OutcomeDetailOperation } from './OutcomeDetailOperation';
import {
    OutcomeDetailOperationFromJSON,
    OutcomeDetailOperationFromJSONTyped,
    OutcomeDetailOperationToJSON,
    OutcomeDetailOperationToJSONTyped,
} from './OutcomeDetailOperation';

/**
 * Represents a generic Outcome Details object;
 * does not have any validation rules or JSON format limitations
 * @export
 * @interface DynamicOutcomeDetails
 */
export interface DynamicOutcomeDetails {
    /**
     * 
     * @type {OutcomeDetailOperation}
     * @memberof DynamicOutcomeDetails
     */
    operation?: OutcomeDetailOperation;
    /**
     * This field categorizes the type of detailed outcome information being provided.
     * @type {string}
     * @memberof DynamicOutcomeDetails
     */
    type?: string;
    /**
     * 
     * Provide additional details of the outreach attempt. This field can be provided as a string or int though only the object form is shown here.
     * @type {any}
     * @memberof DynamicOutcomeDetails
     */
    value?: any | null;
}



/**
 * Check if a given object implements the DynamicOutcomeDetails interface.
 */
export function instanceOfDynamicOutcomeDetails(value: object): value is DynamicOutcomeDetails {
    return true;
}

export function DynamicOutcomeDetailsFromJSON(json: any): DynamicOutcomeDetails {
    return DynamicOutcomeDetailsFromJSONTyped(json, false);
}

export function DynamicOutcomeDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicOutcomeDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['operation'] == null ? undefined : OutcomeDetailOperationFromJSON(json['operation']),
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function DynamicOutcomeDetailsToJSON(json: any): DynamicOutcomeDetails {
    return DynamicOutcomeDetailsToJSONTyped(json, false);
}

export function DynamicOutcomeDetailsToJSONTyped(value?: DynamicOutcomeDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation': OutcomeDetailOperationToJSON(value['operation']),
        'type': value['type'],
        'value': value['value'],
    };
}

