/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a generic Channel Details object;
 * does not have any validation rules or JSON format limitations except where noted below.
 * @export
 * @interface DynamicChannelDetails
 */
export interface DynamicChannelDetails {
    /**
     * Optional; unique identifier for any known id for the channel `type`
     * @type {string}
     * @memberof DynamicChannelDetails
     */
    id?: string | null;
    /**
     * Type of the channel specified in 'value'. Required when Channel is provided.
     *             
     * Recognized types:
     * - "phone_number": Indicates `value` is a phone number; `value` must be in E.164 format (e.g., +14155552671).
     * - "email": Indicates `value` is an email address.
     * - [any other identifier]: Any type not listed above. `value` can be a string, an int or an arbitrary object.
     * @type {string}
     * @memberof DynamicChannelDetails
     */
    type?: string;
    /**
     * 
     * The actual channel used during the outreach attempt. This field can be provided as a string or int though only the object form is shown here.
     * 
     * Examples: +14155552671, name@org.org, @handle.
     * 
     * Required when Channel is provided.
     * @type {any}
     * @memberof DynamicChannelDetails
     */
    value?: any | null;
}

/**
 * Check if a given object implements the DynamicChannelDetails interface.
 */
export function instanceOfDynamicChannelDetails(value: object): value is DynamicChannelDetails {
    return true;
}

export function DynamicChannelDetailsFromJSON(json: any): DynamicChannelDetails {
    return DynamicChannelDetailsFromJSONTyped(json, false);
}

export function DynamicChannelDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicChannelDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function DynamicChannelDetailsToJSON(json: any): DynamicChannelDetails {
    return DynamicChannelDetailsToJSONTyped(json, false);
}

export function DynamicChannelDetailsToJSONTyped(value?: DynamicChannelDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'value': value['value'],
    };
}

