/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents the role of a participant in an event
 * @export
 * @interface EventRole
 */
export interface EventRole {
    /**
     * The role name or description
     * @type {string}
     * @memberof EventRole
     */
    name?: string | null;
}

/**
 * Check if a given object implements the EventRole interface.
 */
export function instanceOfEventRole(value: object): value is EventRole {
    return true;
}

export function EventRoleFromJSON(json: any): EventRole {
    return EventRoleFromJSONTyped(json, false);
}

export function EventRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventRole {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function EventRoleToJSON(json: any): EventRole {
    return EventRoleToJSONTyped(json, false);
}

export function EventRoleToJSONTyped(value?: EventRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

