/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents an identifier and the namespace its value belongs to.
 * @export
 * @interface EventDetails
 */
export interface EventDetails {
    /**
     * The identifier value
     * @type {string}
     * @memberof EventDetails
     */
    id: string;
    /**
     * The namespace the id belongs to, scoped to the field this object appears in: an event namespace in event_id (e.g. "vendor_event_id", "vendor_signup_id"), or a shift namespace in shifts (e.g. "vendor_shift_id").
     * @type {string}
     * @memberof EventDetails
     */
    type: string;
}

/**
 * Check if a given object implements the EventDetails interface.
 */
export function instanceOfEventDetails(value: object): value is EventDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function EventDetailsFromJSON(json: any): EventDetails {
    return EventDetailsFromJSONTyped(json, false);
}

export function EventDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function EventDetailsToJSON(json: any): EventDetails {
    return EventDetailsToJSONTyped(json, false);
}

export function EventDetailsToJSONTyped(value?: EventDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

