/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventSignupStatusValue } from './EventSignupStatusValue';
import {
    EventSignupStatusValueFromJSON,
    EventSignupStatusValueFromJSONTyped,
    EventSignupStatusValueToJSON,
    EventSignupStatusValueToJSONTyped,
} from './EventSignupStatusValue';

/**
 * Represents the status of an event signup
 * @export
 * @interface EventSignupStatus
 */
export interface EventSignupStatus {
    /**
     * 
     * @type {EventSignupStatusValue}
     * @memberof EventSignupStatus
     */
    status: EventSignupStatusValue;
    /**
     * Open string field for vendor-specific reference information
     * @type {string}
     * @memberof EventSignupStatus
     */
    vendorReference?: string | null;
}



/**
 * Check if a given object implements the EventSignupStatus interface.
 */
export function instanceOfEventSignupStatus(value: object): value is EventSignupStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function EventSignupStatusFromJSON(json: any): EventSignupStatus {
    return EventSignupStatusFromJSONTyped(json, false);
}

export function EventSignupStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventSignupStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': EventSignupStatusValueFromJSON(json['status']),
        'vendorReference': json['vendor_reference'] == null ? undefined : json['vendor_reference'],
    };
}

export function EventSignupStatusToJSON(json: any): EventSignupStatus {
    return EventSignupStatusToJSONTyped(json, false);
}

export function EventSignupStatusToJSONTyped(value?: EventSignupStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': EventSignupStatusValueToJSON(value['status']),
        'vendor_reference': value['vendorReference'],
    };
}

