/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventRole } from './EventRole';
import {
    EventRoleFromJSON,
    EventRoleFromJSONTyped,
    EventRoleToJSON,
    EventRoleToJSONTyped,
} from './EventRole';
import type { EventSignupStatus } from './EventSignupStatus';
import {
    EventSignupStatusFromJSON,
    EventSignupStatusFromJSONTyped,
    EventSignupStatusToJSON,
    EventSignupStatusToJSONTyped,
} from './EventSignupStatus';
import type { EventDetails } from './EventDetails';
import {
    EventDetailsFromJSON,
    EventDetailsFromJSONTyped,
    EventDetailsToJSON,
    EventDetailsToJSONTyped,
} from './EventDetails';

/**
 * Represents an event signup captured during an interaction.
 * @export
 * @interface EventSignup
 */
export interface EventSignup {
    /**
     * 
     * @type {EventDetails}
     * @memberof EventSignup
     */
    eventId: EventDetails;
    /**
     * Optional array of shift identifiers for specific shifts within the event
     * @type {Array<EventDetails>}
     * @memberof EventSignup
     */
    shifts?: Array<EventDetails> | null;
    /**
     * 
     * @type {EventRole}
     * @memberof EventSignup
     */
    role?: EventRole;
    /**
     * 
     * @type {EventSignupStatus}
     * @memberof EventSignup
     */
    status?: EventSignupStatus;
}

/**
 * Check if a given object implements the EventSignup interface.
 */
export function instanceOfEventSignup(value: object): value is EventSignup {
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    return true;
}

export function EventSignupFromJSON(json: any): EventSignup {
    return EventSignupFromJSONTyped(json, false);
}

export function EventSignupFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventSignup {
    if (json == null) {
        return json;
    }
    return {
        
        'eventId': EventDetailsFromJSON(json['event_id']),
        'shifts': json['shifts'] == null ? undefined : ((json['shifts'] as Array<any>).map(EventDetailsFromJSON)),
        'role': json['role'] == null ? undefined : EventRoleFromJSON(json['role']),
        'status': json['status'] == null ? undefined : EventSignupStatusFromJSON(json['status']),
    };
}

export function EventSignupToJSON(json: any): EventSignup {
    return EventSignupToJSONTyped(json, false);
}

export function EventSignupToJSONTyped(value?: EventSignup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': EventDetailsToJSON(value['eventId']),
        'shifts': value['shifts'] == null ? undefined : ((value['shifts'] as Array<any>).map(EventDetailsToJSON)),
        'role': EventRoleToJSON(value['role']),
        'status': EventSignupStatusToJSON(value['status']),
    };
}

