/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventSignup } from './EventSignup';
import {
    EventSignupFromJSON,
    EventSignupFromJSONTyped,
    EventSignupToJSON,
    EventSignupToJSONTyped,
} from './EventSignup';

/**
 * Represents an event signup acquired during an interaction.
 * @export
 * @interface EventSignupOutcomeDetails
 */
export interface EventSignupOutcomeDetails {
    /**
     * Describes whether this outcome detail is being created, deleted, or updated. Which operations are accepted varies by outcome type. Defaults to create.
     * @type {string}
     * @memberof EventSignupOutcomeDetails
     */
    operation?: EventSignupOutcomeDetailsOperationEnum;
    /**
     * This field categorizes the type of detailed outcome information being provided.
     * @type {string}
     * @memberof EventSignupOutcomeDetails
     */
    type?: string;
    /**
     * 
     * @type {EventSignup}
     * @memberof EventSignupOutcomeDetails
     */
    value: EventSignup;
}


/**
 * @export
 */
export const EventSignupOutcomeDetailsOperationEnum = {
    Create: 'create',
    Update: 'update'
} as const;
export type EventSignupOutcomeDetailsOperationEnum = typeof EventSignupOutcomeDetailsOperationEnum[keyof typeof EventSignupOutcomeDetailsOperationEnum];


/**
 * Check if a given object implements the EventSignupOutcomeDetails interface.
 */
export function instanceOfEventSignupOutcomeDetails(value: object): value is EventSignupOutcomeDetails {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function EventSignupOutcomeDetailsFromJSON(json: any): EventSignupOutcomeDetails {
    return EventSignupOutcomeDetailsFromJSONTyped(json, false);
}

export function EventSignupOutcomeDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventSignupOutcomeDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['operation'] == null ? undefined : json['operation'],
        'type': json['type'] == null ? undefined : json['type'],
        'value': EventSignupFromJSON(json['value']),
    };
}

export function EventSignupOutcomeDetailsToJSON(json: any): EventSignupOutcomeDetails {
    return EventSignupOutcomeDetailsToJSONTyped(json, false);
}

export function EventSignupOutcomeDetailsToJSONTyped(value?: EventSignupOutcomeDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation': value['operation'],
        'type': value['type'],
        'value': EventSignupToJSON(value['value']),
    };
}

