/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of an interaction's progress through the Exchange data pipeline.
 * @export
 */
export const ExchangeInteractionStatus = {
    Queued: 'Queued',
    Processed: 'Processed',
    PartiallyOrFullyUnsupported: 'PartiallyOrFullyUnsupported',
    Error: 'Error',
    Unknown: 'Unknown'
} as const;
export type ExchangeInteractionStatus = typeof ExchangeInteractionStatus[keyof typeof ExchangeInteractionStatus];


export function instanceOfExchangeInteractionStatus(value: any): boolean {
    for (const key in ExchangeInteractionStatus) {
        if (Object.prototype.hasOwnProperty.call(ExchangeInteractionStatus, key)) {
            if (ExchangeInteractionStatus[key as keyof typeof ExchangeInteractionStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ExchangeInteractionStatusFromJSON(json: any): ExchangeInteractionStatus {
    return ExchangeInteractionStatusFromJSONTyped(json, false);
}

export function ExchangeInteractionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeInteractionStatus {
    return json as ExchangeInteractionStatus;
}

export function ExchangeInteractionStatusToJSON(value?: ExchangeInteractionStatus | null): any {
    return value as any;
}

export function ExchangeInteractionStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ExchangeInteractionStatus {
    return value as ExchangeInteractionStatus;
}

