/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExchangeInteractionStatusDto } from './ExchangeInteractionStatusDto';
import {
    ExchangeInteractionStatusDtoFromJSON,
    ExchangeInteractionStatusDtoFromJSONTyped,
    ExchangeInteractionStatusDtoToJSON,
    ExchangeInteractionStatusDtoToJSONTyped,
} from './ExchangeInteractionStatusDto';
import type { MinervaMetadataDto } from './MinervaMetadataDto';
import {
    MinervaMetadataDtoFromJSON,
    MinervaMetadataDtoFromJSONTyped,
    MinervaMetadataDtoToJSON,
    MinervaMetadataDtoToJSONTyped,
} from './MinervaMetadataDto';

/**
 * Extends Minerva.Dto.Api.GetResponseDto`1 with cursor-based pagination support.
 * @export
 * @interface ExchangeInteractionStatusDtoCursorPaginatedResponseDto
 */
export interface ExchangeInteractionStatusDtoCursorPaginatedResponseDto {
    /**
     * 
     * @type {MinervaMetadataDto}
     * @memberof ExchangeInteractionStatusDtoCursorPaginatedResponseDto
     */
    metadata?: MinervaMetadataDto;
    /**
     * 
     * @type {Array<ExchangeInteractionStatusDto>}
     * @memberof ExchangeInteractionStatusDtoCursorPaginatedResponseDto
     */
    data?: Array<ExchangeInteractionStatusDto>;
    /**
     * Opaque cursor token for fetching the next page. Null if there are no more results.
     * @type {string}
     * @memberof ExchangeInteractionStatusDtoCursorPaginatedResponseDto
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the ExchangeInteractionStatusDtoCursorPaginatedResponseDto interface.
 */
export function instanceOfExchangeInteractionStatusDtoCursorPaginatedResponseDto(value: object): value is ExchangeInteractionStatusDtoCursorPaginatedResponseDto {
    return true;
}

export function ExchangeInteractionStatusDtoCursorPaginatedResponseDtoFromJSON(json: any): ExchangeInteractionStatusDtoCursorPaginatedResponseDto {
    return ExchangeInteractionStatusDtoCursorPaginatedResponseDtoFromJSONTyped(json, false);
}

export function ExchangeInteractionStatusDtoCursorPaginatedResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeInteractionStatusDtoCursorPaginatedResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : MinervaMetadataDtoFromJSON(json['metadata']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ExchangeInteractionStatusDtoFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
    };
}

export function ExchangeInteractionStatusDtoCursorPaginatedResponseDtoToJSON(json: any): ExchangeInteractionStatusDtoCursorPaginatedResponseDto {
    return ExchangeInteractionStatusDtoCursorPaginatedResponseDtoToJSONTyped(json, false);
}

export function ExchangeInteractionStatusDtoCursorPaginatedResponseDtoToJSONTyped(value?: ExchangeInteractionStatusDtoCursorPaginatedResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': MinervaMetadataDtoToJSON(value['metadata']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ExchangeInteractionStatusDtoToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

