/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExternalApiKeyStatus = {
    Unknown: 'Unknown',
    Active: 'Active'
} as const;
export type ExternalApiKeyStatus = typeof ExternalApiKeyStatus[keyof typeof ExternalApiKeyStatus];


export function instanceOfExternalApiKeyStatus(value: any): boolean {
    for (const key in ExternalApiKeyStatus) {
        if (Object.prototype.hasOwnProperty.call(ExternalApiKeyStatus, key)) {
            if (ExternalApiKeyStatus[key as keyof typeof ExternalApiKeyStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ExternalApiKeyStatusFromJSON(json: any): ExternalApiKeyStatus {
    return ExternalApiKeyStatusFromJSONTyped(json, false);
}

export function ExternalApiKeyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalApiKeyStatus {
    return json as ExternalApiKeyStatus;
}

export function ExternalApiKeyStatusToJSON(value?: ExternalApiKeyStatus | null): any {
    return value as any;
}

export function ExternalApiKeyStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ExternalApiKeyStatus {
    return value as ExternalApiKeyStatus;
}

