/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExternalApiKeyType = {
    Van: 'Van'
} as const;
export type ExternalApiKeyType = typeof ExternalApiKeyType[keyof typeof ExternalApiKeyType];


export function instanceOfExternalApiKeyType(value: any): boolean {
    for (const key in ExternalApiKeyType) {
        if (Object.prototype.hasOwnProperty.call(ExternalApiKeyType, key)) {
            if (ExternalApiKeyType[key as keyof typeof ExternalApiKeyType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ExternalApiKeyTypeFromJSON(json: any): ExternalApiKeyType {
    return ExternalApiKeyTypeFromJSONTyped(json, false);
}

export function ExternalApiKeyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalApiKeyType {
    return json as ExternalApiKeyType;
}

export function ExternalApiKeyTypeToJSON(value?: ExternalApiKeyType | null): any {
    return value as any;
}

export function ExternalApiKeyTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ExternalApiKeyType {
    return value as ExternalApiKeyType;
}

