/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExternalTransactionStatus = {
    Received: 'Received',
    Processing: 'Processing',
    Success: 'Success',
    Failed: 'Failed',
    Invalid: 'Invalid',
    Duplicate: 'Duplicate',
    InternalError: 'InternalError'
} as const;
export type ExternalTransactionStatus = typeof ExternalTransactionStatus[keyof typeof ExternalTransactionStatus];


export function instanceOfExternalTransactionStatus(value: any): boolean {
    for (const key in ExternalTransactionStatus) {
        if (Object.prototype.hasOwnProperty.call(ExternalTransactionStatus, key)) {
            if (ExternalTransactionStatus[key as keyof typeof ExternalTransactionStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ExternalTransactionStatusFromJSON(json: any): ExternalTransactionStatus {
    return ExternalTransactionStatusFromJSONTyped(json, false);
}

export function ExternalTransactionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalTransactionStatus {
    return json as ExternalTransactionStatus;
}

export function ExternalTransactionStatusToJSON(value?: ExternalTransactionStatus | null): any {
    return value as any;
}

export function ExternalTransactionStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ExternalTransactionStatus {
    return value as ExternalTransactionStatus;
}

