/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents an initiative associated with an interaction, such as a campaign identifier.
 * @export
 * @interface InitiativeDto
 */
export interface InitiativeDto {
    /**
     * Type of the initiative identifier specified in 'id'.
     * @type {string}
     * @memberof InitiativeDto
     */
    type?: string | null;
    /**
     * The actual initiative identifier, such as a campaign ID.
     * @type {string}
     * @memberof InitiativeDto
     */
    id?: string | null;
    /**
     * Descriptive name or title for the initiative.
     * @type {string}
     * @memberof InitiativeDto
     */
    name?: string | null;
}

/**
 * Check if a given object implements the InitiativeDto interface.
 */
export function instanceOfInitiativeDto(value: object): value is InitiativeDto {
    return true;
}

export function InitiativeDtoFromJSON(json: any): InitiativeDto {
    return InitiativeDtoFromJSONTyped(json, false);
}

export function InitiativeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InitiativeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function InitiativeDtoToJSON(json: any): InitiativeDto {
    return InitiativeDtoToJSONTyped(json, false);
}

export function InitiativeDtoToJSONTyped(value?: InitiativeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'name': value['name'],
    };
}

