/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AddressChannelDetails } from './AddressChannelDetails';
import {
    instanceOfAddressChannelDetails,
    AddressChannelDetailsFromJSON,
    AddressChannelDetailsFromJSONTyped,
    AddressChannelDetailsToJSON,
} from './AddressChannelDetails';
import type { DynamicChannelDetails } from './DynamicChannelDetails';
import {
    instanceOfDynamicChannelDetails,
    DynamicChannelDetailsFromJSON,
    DynamicChannelDetailsFromJSONTyped,
    DynamicChannelDetailsToJSON,
} from './DynamicChannelDetails';

/**
 * @type InteractionDtoChannel
 * Channel-of-contact details used during the outreach attempt.
 * If the `type` is recognized as an Address Channel (type = "address"), the `value` will be deserialized to that object type.
 * Other string-based types have specific validation documented in the "Channel" section below, like "phone_number".
 * If the `type` is unrecognized, the payload will be deserialized to an unvalidated, loosely typed object for flexibility.
 * @export
 */
export type InteractionDtoChannel = { type: 'address' } & AddressChannelDetails | { type: 'example_type' } & DynamicChannelDetails;

export function InteractionDtoChannelFromJSON(json: any): InteractionDtoChannel {
    return InteractionDtoChannelFromJSONTyped(json, false);
}

export function InteractionDtoChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): InteractionDtoChannel {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'address':
            return Object.assign({}, AddressChannelDetailsFromJSONTyped(json, true), { type: 'address' } as const);
        case 'example_type':
            return Object.assign({}, DynamicChannelDetailsFromJSONTyped(json, true), { type: 'example_type' } as const);
        default:
            throw new Error(`No variant of InteractionDtoChannel exists with 'type=${json['type']}'`);
    }
}

export function InteractionDtoChannelToJSON(json: any): any {
    return InteractionDtoChannelToJSONTyped(json, false);
}

export function InteractionDtoChannelToJSONTyped(value?: InteractionDtoChannel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'address':
            return Object.assign({}, AddressChannelDetailsToJSON(value), { type: 'address' } as const);
        case 'example_type':
            return Object.assign({}, DynamicChannelDetailsToJSON(value), { type: 'example_type' } as const);
        default:
            throw new Error(`No variant of InteractionDtoChannel exists with 'type=${value['type']}'`);
    }

}

