/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ActivistCodeOutcomeDetails } from './ActivistCodeOutcomeDetails';
import {
    instanceOfActivistCodeOutcomeDetails,
    ActivistCodeOutcomeDetailsFromJSON,
    ActivistCodeOutcomeDetailsFromJSONTyped,
    ActivistCodeOutcomeDetailsToJSON,
} from './ActivistCodeOutcomeDetails';
import type { CommunicationConsentOutcomeDetails } from './CommunicationConsentOutcomeDetails';
import {
    instanceOfCommunicationConsentOutcomeDetails,
    CommunicationConsentOutcomeDetailsFromJSON,
    CommunicationConsentOutcomeDetailsFromJSONTyped,
    CommunicationConsentOutcomeDetailsToJSON,
} from './CommunicationConsentOutcomeDetails';
import type { DynamicOutcomeDetails } from './DynamicOutcomeDetails';
import {
    instanceOfDynamicOutcomeDetails,
    DynamicOutcomeDetailsFromJSON,
    DynamicOutcomeDetailsFromJSONTyped,
    DynamicOutcomeDetailsToJSON,
} from './DynamicOutcomeDetails';
import type { EventSignupOutcomeDetails } from './EventSignupOutcomeDetails';
import {
    instanceOfEventSignupOutcomeDetails,
    EventSignupOutcomeDetailsFromJSON,
    EventSignupOutcomeDetailsFromJSONTyped,
    EventSignupOutcomeDetailsToJSON,
} from './EventSignupOutcomeDetails';
import type { SurveyResponseOutcomeDetails } from './SurveyResponseOutcomeDetails';
import {
    instanceOfSurveyResponseOutcomeDetails,
    SurveyResponseOutcomeDetailsFromJSON,
    SurveyResponseOutcomeDetailsFromJSONTyped,
    SurveyResponseOutcomeDetailsToJSON,
} from './SurveyResponseOutcomeDetails';

/**
 * @type InteractionDtoOutcomesDetailedInner
 * 
 * @export
 */
export type InteractionDtoOutcomesDetailedInner = { type: 'activist_code' } & ActivistCodeOutcomeDetails | { type: 'communication_consent' } & CommunicationConsentOutcomeDetails | { type: 'event_signup' } & EventSignupOutcomeDetails | { type: 'example_type' } & DynamicOutcomeDetails | { type: 'survey_response' } & SurveyResponseOutcomeDetails;

export function InteractionDtoOutcomesDetailedInnerFromJSON(json: any): InteractionDtoOutcomesDetailedInner {
    return InteractionDtoOutcomesDetailedInnerFromJSONTyped(json, false);
}

export function InteractionDtoOutcomesDetailedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): InteractionDtoOutcomesDetailedInner {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'activist_code':
            return Object.assign({}, ActivistCodeOutcomeDetailsFromJSONTyped(json, true), { type: 'activist_code' } as const);
        case 'communication_consent':
            return Object.assign({}, CommunicationConsentOutcomeDetailsFromJSONTyped(json, true), { type: 'communication_consent' } as const);
        case 'event_signup':
            return Object.assign({}, EventSignupOutcomeDetailsFromJSONTyped(json, true), { type: 'event_signup' } as const);
        case 'example_type':
            return Object.assign({}, DynamicOutcomeDetailsFromJSONTyped(json, true), { type: 'example_type' } as const);
        case 'survey_response':
            return Object.assign({}, SurveyResponseOutcomeDetailsFromJSONTyped(json, true), { type: 'survey_response' } as const);
        default:
            throw new Error(`No variant of InteractionDtoOutcomesDetailedInner exists with 'type=${json['type']}'`);
    }
}

export function InteractionDtoOutcomesDetailedInnerToJSON(json: any): any {
    return InteractionDtoOutcomesDetailedInnerToJSONTyped(json, false);
}

export function InteractionDtoOutcomesDetailedInnerToJSONTyped(value?: InteractionDtoOutcomesDetailedInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'activist_code':
            return Object.assign({}, ActivistCodeOutcomeDetailsToJSON(value), { type: 'activist_code' } as const);
        case 'communication_consent':
            return Object.assign({}, CommunicationConsentOutcomeDetailsToJSON(value), { type: 'communication_consent' } as const);
        case 'event_signup':
            return Object.assign({}, EventSignupOutcomeDetailsToJSON(value), { type: 'event_signup' } as const);
        case 'example_type':
            return Object.assign({}, DynamicOutcomeDetailsToJSON(value), { type: 'example_type' } as const);
        case 'survey_response':
            return Object.assign({}, SurveyResponseOutcomeDetailsToJSON(value), { type: 'survey_response' } as const);
        default:
            throw new Error(`No variant of InteractionDtoOutcomesDetailedInner exists with 'type=${value['type']}'`);
    }

}

