/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * VAN-specific data for an interaction. Must be provided if if the Interactions API Key used on the request
 * is configured with VAN as a destination.
 * @export
 * @interface InteractionVanFieldsDto
 */
export interface InteractionVanFieldsDto {
    /**
     * VAN contact type ID. Must match a Contact Type accessible to the destination VAN committee.
     * See https://docs.ngpvan.com/reference/canvassresponsescontacttypes for details on retrieving accessible contact types.
     * @type {string}
     * @memberof InteractionVanFieldsDto
     */
    contactTypeId?: string;
    /**
     * VAN contact attempt result code, representing the result of that contact attempt. Result code availibility varies based on
     * contact type, so this value must represent a code that is available to the Contact Type ID specified above.
     * See https://docs.ngpvan.com/reference/canvassresponsesresultcodes to view Result Codes accessible to the destination VAN committee.
     * @type {string}
     * @memberof InteractionVanFieldsDto
     */
    resultCodeId?: string | null;
}

/**
 * Check if a given object implements the InteractionVanFieldsDto interface.
 */
export function instanceOfInteractionVanFieldsDto(value: object): value is InteractionVanFieldsDto {
    return true;
}

export function InteractionVanFieldsDtoFromJSON(json: any): InteractionVanFieldsDto {
    return InteractionVanFieldsDtoFromJSONTyped(json, false);
}

export function InteractionVanFieldsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InteractionVanFieldsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'contactTypeId': json['contactTypeId'] == null ? undefined : json['contactTypeId'],
        'resultCodeId': json['resultCodeId'] == null ? undefined : json['resultCodeId'],
    };
}

export function InteractionVanFieldsDtoToJSON(json: any): InteractionVanFieldsDto {
    return InteractionVanFieldsDtoToJSONTyped(json, false);
}

export function InteractionVanFieldsDtoToJSONTyped(value?: InteractionVanFieldsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contactTypeId': value['contactTypeId'],
        'resultCodeId': value['resultCodeId'],
    };
}

