/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InteractionErrorDto
 */
export interface InteractionErrorDto {
    /**
     * 
     * @type {string}
     * @memberof InteractionErrorDto
     */
    field?: string;
    /**
     * 
     * @type {string}
     * @memberof InteractionErrorDto
     */
    errorMessage?: string;
}

/**
 * Check if a given object implements the InteractionErrorDto interface.
 */
export function instanceOfInteractionErrorDto(value: object): value is InteractionErrorDto {
    return true;
}

export function InteractionErrorDtoFromJSON(json: any): InteractionErrorDto {
    return InteractionErrorDtoFromJSONTyped(json, false);
}

export function InteractionErrorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InteractionErrorDto {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
    };
}

export function InteractionErrorDtoToJSON(json: any): InteractionErrorDto {
    return InteractionErrorDtoToJSONTyped(json, false);
}

export function InteractionErrorDtoToJSONTyped(value?: InteractionErrorDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'errorMessage': value['errorMessage'],
    };
}

