/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AcceptedInteractionsDto } from './AcceptedInteractionsDto';
import {
    AcceptedInteractionsDtoFromJSON,
    AcceptedInteractionsDtoFromJSONTyped,
    AcceptedInteractionsDtoToJSON,
    AcceptedInteractionsDtoToJSONTyped,
} from './AcceptedInteractionsDto';
import type { RejectedInteractionsDto } from './RejectedInteractionsDto';
import {
    RejectedInteractionsDtoFromJSON,
    RejectedInteractionsDtoFromJSONTyped,
    RejectedInteractionsDtoToJSON,
    RejectedInteractionsDtoToJSONTyped,
} from './RejectedInteractionsDto';

/**
 * Represents the result of processing a batch of interactions, including accepted and rejected interactions.
 * @export
 * @interface InteractionsBatchResultDto
 */
export interface InteractionsBatchResultDto {
    /**
     * DDx API request identifier, provided as X-Correlation-Id on interactions responses for use linking all interactions in a request.
     * @type {string}
     * @memberof InteractionsBatchResultDto
     */
    correlationId?: string;
    /**
     * Total number of interactions in the batch.
     * @type {number}
     * @memberof InteractionsBatchResultDto
     */
    totalInteractions?: number;
    /**
     * 
     * @type {AcceptedInteractionsDto}
     * @memberof InteractionsBatchResultDto
     */
    acceptedInteractions?: AcceptedInteractionsDto;
    /**
     * 
     * @type {RejectedInteractionsDto}
     * @memberof InteractionsBatchResultDto
     */
    rejectedInteractions?: RejectedInteractionsDto;
}

/**
 * Check if a given object implements the InteractionsBatchResultDto interface.
 */
export function instanceOfInteractionsBatchResultDto(value: object): value is InteractionsBatchResultDto {
    return true;
}

export function InteractionsBatchResultDtoFromJSON(json: any): InteractionsBatchResultDto {
    return InteractionsBatchResultDtoFromJSONTyped(json, false);
}

export function InteractionsBatchResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InteractionsBatchResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'correlationId': json['correlationId'] == null ? undefined : json['correlationId'],
        'totalInteractions': json['totalInteractions'] == null ? undefined : json['totalInteractions'],
        'acceptedInteractions': json['acceptedInteractions'] == null ? undefined : AcceptedInteractionsDtoFromJSON(json['acceptedInteractions']),
        'rejectedInteractions': json['rejectedInteractions'] == null ? undefined : RejectedInteractionsDtoFromJSON(json['rejectedInteractions']),
    };
}

export function InteractionsBatchResultDtoToJSON(json: any): InteractionsBatchResultDto {
    return InteractionsBatchResultDtoToJSONTyped(json, false);
}

export function InteractionsBatchResultDtoToJSONTyped(value?: InteractionsBatchResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'correlationId': value['correlationId'],
        'totalInteractions': value['totalInteractions'],
        'acceptedInteractions': AcceptedInteractionsDtoToJSON(value['acceptedInteractions']),
        'rejectedInteractions': RejectedInteractionsDtoToJSON(value['rejectedInteractions']),
    };
}

