/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MinervaMetadataDto
 */
export interface MinervaMetadataDto {
    /**
     * Number of records returned in the response `data` array
     * @type {number}
     * @memberof MinervaMetadataDto
     */
    count?: number;
}

/**
 * Check if a given object implements the MinervaMetadataDto interface.
 */
export function instanceOfMinervaMetadataDto(value: object): value is MinervaMetadataDto {
    return true;
}

export function MinervaMetadataDtoFromJSON(json: any): MinervaMetadataDto {
    return MinervaMetadataDtoFromJSONTyped(json, false);
}

export function MinervaMetadataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinervaMetadataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function MinervaMetadataDtoToJSON(json: any): MinervaMetadataDto {
    return MinervaMetadataDtoToJSONTyped(json, false);
}

export function MinervaMetadataDtoToJSONTyped(value?: MinervaMetadataDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
    };
}

