/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a person involved in an interaction, including their identifier and optional contact information.
 * @export
 * @interface PersonIdentifier
 */
export interface PersonIdentifier {
    /**
     * A primary identifier for tracking individual voters. This can be an integer (e.g. for DNC person_ids),
     * a string (for UUIDs, phone numbers), or other identifier formats depending on the source system.
     * Used to link voter records across different data sources and track in-state voter history over time.
     * @type {string}
     * @memberof PersonIdentifier
     */
    id: string;
    /**
     * Type of identifier or source system that generated the id.
     * Examples include "VAN", "phone", "slimCRM", "DNC", "SOS", etc. 
     * This field indicates the origin or authority of the person identifier.
     * @type {string}
     * @memberof PersonIdentifier
     */
    type: string;
}

/**
 * Check if a given object implements the PersonIdentifier interface.
 */
export function instanceOfPersonIdentifier(value: object): value is PersonIdentifier {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PersonIdentifierFromJSON(json: any): PersonIdentifier {
    return PersonIdentifierFromJSONTyped(json, false);
}

export function PersonIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonIdentifier {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function PersonIdentifierToJSON(json: any): PersonIdentifier {
    return PersonIdentifierToJSONTyped(json, false);
}

export function PersonIdentifierToJSONTyped(value?: PersonIdentifier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

