/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InteractionErrorDto } from './InteractionErrorDto';
import {
    InteractionErrorDtoFromJSON,
    InteractionErrorDtoFromJSONTyped,
    InteractionErrorDtoToJSON,
    InteractionErrorDtoToJSONTyped,
} from './InteractionErrorDto';

/**
 * Represents a rejected interaction with its associated errors.
 * @export
 * @interface RejectedInteractionDto
 */
export interface RejectedInteractionDto {
    /**
     * ID used to identify the interaction; ID will have been returned from the initial publish response.
     * @type {string}
     * @memberof RejectedInteractionDto
     */
    interactionId?: string;
    /**
     * Index of the rejected interaction in the batch.
     * @type {number}
     * @memberof RejectedInteractionDto
     */
    index?: number;
    /**
     * List of errors associated with the rejected interaction.
     * @type {Array<InteractionErrorDto>}
     * @memberof RejectedInteractionDto
     */
    errors?: Array<InteractionErrorDto>;
}

/**
 * Check if a given object implements the RejectedInteractionDto interface.
 */
export function instanceOfRejectedInteractionDto(value: object): value is RejectedInteractionDto {
    return true;
}

export function RejectedInteractionDtoFromJSON(json: any): RejectedInteractionDto {
    return RejectedInteractionDtoFromJSONTyped(json, false);
}

export function RejectedInteractionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RejectedInteractionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'interactionId': json['interactionId'] == null ? undefined : json['interactionId'],
        'index': json['index'] == null ? undefined : json['index'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(InteractionErrorDtoFromJSON)),
    };
}

export function RejectedInteractionDtoToJSON(json: any): RejectedInteractionDto {
    return RejectedInteractionDtoToJSONTyped(json, false);
}

export function RejectedInteractionDtoToJSONTyped(value?: RejectedInteractionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interactionId': value['interactionId'],
        'index': value['index'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(InteractionErrorDtoToJSON)),
    };
}

