/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleMovementAppDto
 */
export interface SimpleMovementAppDto {
    /**
     * 
     * @type {string}
     * @memberof SimpleMovementAppDto
     */
    movementAppId: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleMovementAppDto
     */
    name: string;
}

/**
 * Check if a given object implements the SimpleMovementAppDto interface.
 */
export function instanceOfSimpleMovementAppDto(value: object): value is SimpleMovementAppDto {
    if (!('movementAppId' in value) || value['movementAppId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SimpleMovementAppDtoFromJSON(json: any): SimpleMovementAppDto {
    return SimpleMovementAppDtoFromJSONTyped(json, false);
}

export function SimpleMovementAppDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleMovementAppDto {
    if (json == null) {
        return json;
    }
    return {
        
        'movementAppId': json['movementAppId'],
        'name': json['name'],
    };
}

export function SimpleMovementAppDtoToJSON(json: any): SimpleMovementAppDto {
    return SimpleMovementAppDtoToJSONTyped(json, false);
}

export function SimpleMovementAppDtoToJSONTyped(value?: SimpleMovementAppDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'movementAppId': value['movementAppId'],
        'name': value['name'],
    };
}

