/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleDestinationDto
 */
export interface SimpleDestinationDto {
    /**
     * Unique identifier for the destination
     * @type {number}
     * @memberof SimpleDestinationDto
     */
    id: number;
    /**
     * Display name for the destination
     * @type {string}
     * @memberof SimpleDestinationDto
     */
    name?: string | null;
    /**
     * Indicator of whether the destination integrates with NGP VAN
     * and requires an associated VAN External API Key
     * @type {boolean}
     * @memberof SimpleDestinationDto
     */
    isVanDestination?: boolean;
}

/**
 * Check if a given object implements the SimpleDestinationDto interface.
 */
export function instanceOfSimpleDestinationDto(value: object): value is SimpleDestinationDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SimpleDestinationDtoFromJSON(json: any): SimpleDestinationDto {
    return SimpleDestinationDtoFromJSONTyped(json, false);
}

export function SimpleDestinationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleDestinationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'isVanDestination': json['isVanDestination'] == null ? undefined : json['isVanDestination'],
    };
}

export function SimpleDestinationDtoToJSON(json: any): SimpleDestinationDto {
    return SimpleDestinationDtoToJSONTyped(json, false);
}

export function SimpleDestinationDtoToJSONTyped(value?: SimpleDestinationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'isVanDestination': value['isVanDestination'],
    };
}

