/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SurveyResponse
 */
export interface SurveyResponse {
    /**
     * Unique identifier for the survey question being asked;
     * the value may be retrieved from the system that sourced the question
     * @type {string}
     * @memberof SurveyResponse
     */
    questionId?: string | null;
    /**
     * The question text presented during an interaction
     * @type {string}
     * @memberof SurveyResponse
     */
    questionText: string;
    /**
     * Unique identifier for the survey response associated with the question;
     * the value may be retrieved from the system that sourced the question
     * @type {string}
     * @memberof SurveyResponse
     */
    responseId?: string | null;
    /**
     * An answer to the question.
     * Required when Survey Question text is provided.
     * @type {string}
     * @memberof SurveyResponse
     */
    responseText: string;
}

/**
 * Check if a given object implements the SurveyResponse interface.
 */
export function instanceOfSurveyResponse(value: object): value is SurveyResponse {
    if (!('questionText' in value) || value['questionText'] === undefined) return false;
    if (!('responseText' in value) || value['responseText'] === undefined) return false;
    return true;
}

export function SurveyResponseFromJSON(json: any): SurveyResponse {
    return SurveyResponseFromJSONTyped(json, false);
}

export function SurveyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SurveyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'questionId': json['questionId'] == null ? undefined : json['questionId'],
        'questionText': json['questionText'],
        'responseId': json['responseId'] == null ? undefined : json['responseId'],
        'responseText': json['responseText'],
    };
}

export function SurveyResponseToJSON(json: any): SurveyResponse {
    return SurveyResponseToJSONTyped(json, false);
}

export function SurveyResponseToJSONTyped(value?: SurveyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questionId': value['questionId'],
        'questionText': value['questionText'],
        'responseId': value['responseId'],
        'responseText': value['responseText'],
    };
}

