/* tslint:disable */
/* eslint-disable */
/**
 * Interactions API
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VanDatabaseMode = {
    MyVoters: 'MyVoters',
    MyCampaign: 'MyCampaign'
} as const;
export type VanDatabaseMode = typeof VanDatabaseMode[keyof typeof VanDatabaseMode];


export function instanceOfVanDatabaseMode(value: any): boolean {
    for (const key in VanDatabaseMode) {
        if (Object.prototype.hasOwnProperty.call(VanDatabaseMode, key)) {
            if (VanDatabaseMode[key as keyof typeof VanDatabaseMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VanDatabaseModeFromJSON(json: any): VanDatabaseMode {
    return VanDatabaseModeFromJSONTyped(json, false);
}

export function VanDatabaseModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VanDatabaseMode {
    return json as VanDatabaseMode;
}

export function VanDatabaseModeToJSON(value?: VanDatabaseMode | null): any {
    return value as any;
}

export function VanDatabaseModeToJSONTyped(value: any, ignoreDiscriminator: boolean): VanDatabaseMode {
    return value as VanDatabaseMode;
}

