=begin
#Interactions API

#Interactions API documentation

The version of the OpenAPI document: v1
Contact: api@demexchange.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module DdxInteractionsApi
  class ContactMethod
    UNKNOWN = "unknown".freeze
    MAIL = "mail".freeze
    LETTER = "letter".freeze
    DIGITAL_AD = "digital_ad".freeze
    EMAIL = "email".freeze
    TEXT = "text".freeze
    TEXT_BROADCAST = "text_broadcast".freeze
    ROBO_CALL = "robo_call".freeze
    DIALER_CALL = "dialer_call".freeze
    PHONE_CALL = "phone_call".freeze
    DOOR_KNOCK = "door_knock".freeze
    EVENT = "Event".freeze
    HOT_SPOT = "hot_spot".freeze
    ONE_ON_ONE = "one_on_one".freeze
    WEB_INTERACTION = "web_interaction".freeze

    def self.all_vars
      @all_vars ||= [UNKNOWN, MAIL, LETTER, DIGITAL_AD, EMAIL, TEXT, TEXT_BROADCAST, ROBO_CALL, DIALER_CALL, PHONE_CALL, DOOR_KNOCK, EVENT, HOT_SPOT, ONE_ON_ONE, WEB_INTERACTION].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ContactMethod.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ContactMethod"
    end
  end
end
