=begin
#Interactions API

#Interactions API documentation

The version of the OpenAPI document: v1
Contact: api@demexchange.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module DdxInteractionsApi
  class EventSignupStatusValue
    SCHEDULED = "scheduled".freeze
    WAITLISTED = "waitlisted".freeze
    INVITED = "invited".freeze
    COMPLETED = "completed".freeze
    CONFIRMED = "confirmed".freeze
    CANCELLED = "cancelled".freeze
    NO_SHOW = "no_show".freeze
    PARTIAL = "partial".freeze
    CANNOT_ATTEND = "cannot_attend".freeze

    def self.all_vars
      @all_vars ||= [SCHEDULED, WAITLISTED, INVITED, COMPLETED, CONFIRMED, CANCELLED, NO_SHOW, PARTIAL, CANNOT_ATTEND].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if EventSignupStatusValue.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #EventSignupStatusValue"
    end
  end
end
