=begin
#Interactions API

#Interactions API documentation

The version of the OpenAPI document: v1
Contact: api@demexchange.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module DdxInteractionsApi
  class Outcome
    UNKNOWN = "unknown".freeze
    CLICKED_LINK = "clicked_link".freeze
    EMAIL_OPENED = "email_opened".freeze
    SUBMITTED_FORM = "submitted_form".freeze
    SUCCESSFUL_CONTACT = "successful_contact".freeze
    DECEASED = "deceased".freeze
    DELIVERABILITY_ERROR = "deliverability_error".freeze
    PERMANENTLY_UNDELIVERABLE = "permanently_undeliverable".freeze
    INACCESSIBLE = "inaccessible".freeze
    LANGUAGE_BARRIER = "language_barrier".freeze
    MOVED = "moved".freeze
    NO_ANSWER = "no_answer".freeze
    WRONG_NUMBER = "wrong_number".freeze
    HOSTILE = "hostile".freeze
    MARKED_SPAM = "marked_spam".freeze
    REFUSED = "refused".freeze
    DELIVERED = "delivered".freeze
    LIT_DROP = "lit_drop".freeze
    LEFT_MESSAGE = "left_message".freeze
    OTHER = "other".freeze

    def self.all_vars
      @all_vars ||= [UNKNOWN, CLICKED_LINK, EMAIL_OPENED, SUBMITTED_FORM, SUCCESSFUL_CONTACT, DECEASED, DELIVERABILITY_ERROR, PERMANENTLY_UNDELIVERABLE, INACCESSIBLE, LANGUAGE_BARRIER, MOVED, NO_ANSWER, WRONG_NUMBER, HOSTILE, MARKED_SPAM, REFUSED, DELIVERED, LIT_DROP, LEFT_MESSAGE, OTHER].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if Outcome.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Outcome"
    end
  end
end
