=begin
#Interactions API

#Interactions API documentation

The version of the OpenAPI document: v1
Contact: api@demexchange.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module DdxInteractionsApi
  class VanDatabaseMode
    MY_VOTERS = "MyVoters".freeze
    MY_CAMPAIGN = "MyCampaign".freeze

    def self.all_vars
      @all_vars ||= [MY_VOTERS, MY_CAMPAIGN].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if VanDatabaseMode.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #VanDatabaseMode"
    end
  end
end
