/*
 * Interactions API
 *
 * Interactions API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: api@demexchange.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Ddx.InteractionsApi.Client;
using Ddx.InteractionsApi.Model;

namespace Ddx.InteractionsApi.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IInteractionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Exchange pipeline statuses by correlation or interaction ID
        /// </summary>
        /// <remarks>
        /// Returns Exchange pipeline statuses filtered by either correlationId or interactionId.  Supports cursor-based pagination.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="correlationId">The correlation ID returned from the initial publish response. (optional)</param>
        /// <param name="interactionId">The interaction&#39;s unique identifier (GUID). (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <returns>ExchangeInteractionStatusDtoCursorPaginatedResponseDto</returns>
        ExchangeInteractionStatusDtoCursorPaginatedResponseDto VversionInteractionsExchangeStatusGet(string version, string? correlationId = default(string?), Guid? interactionId = default(Guid?), string? cursor = default(string?), int? limit = default(int?));

        /// <summary>
        /// Get Exchange pipeline statuses by correlation or interaction ID
        /// </summary>
        /// <remarks>
        /// Returns Exchange pipeline statuses filtered by either correlationId or interactionId.  Supports cursor-based pagination.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="correlationId">The correlation ID returned from the initial publish response. (optional)</param>
        /// <param name="interactionId">The interaction&#39;s unique identifier (GUID). (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <returns>ApiResponse of ExchangeInteractionStatusDtoCursorPaginatedResponseDto</returns>
        ApiResponse<ExchangeInteractionStatusDtoCursorPaginatedResponseDto> VversionInteractionsExchangeStatusGetWithHttpInfo(string version, string? correlationId = default(string?), Guid? interactionId = default(Guid?), string? cursor = default(string?), int? limit = default(int?));
        /// <summary>
        /// Get Exchange pipeline statuses by date range
        /// </summary>
        /// <remarks>
        /// Returns Exchange pipeline statuses for interactions published within the specified date range.  Supports cursor-based pagination. Maximum date range is 30 days.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range (inclusive, UTC). (optional)</param>
        /// <param name="endDate">End of date range (inclusive, UTC). Defaults to current UTC time. (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <returns>ExchangeInteractionStatusDtoCursorPaginatedResponseDto</returns>
        ExchangeInteractionStatusDtoCursorPaginatedResponseDto VversionInteractionsExchangeStatusRangeGet(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), string? cursor = default(string?), int? limit = default(int?));

        /// <summary>
        /// Get Exchange pipeline statuses by date range
        /// </summary>
        /// <remarks>
        /// Returns Exchange pipeline statuses for interactions published within the specified date range.  Supports cursor-based pagination. Maximum date range is 30 days.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range (inclusive, UTC). (optional)</param>
        /// <param name="endDate">End of date range (inclusive, UTC). Defaults to current UTC time. (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <returns>ApiResponse of ExchangeInteractionStatusDtoCursorPaginatedResponseDto</returns>
        ApiResponse<ExchangeInteractionStatusDtoCursorPaginatedResponseDto> VversionInteractionsExchangeStatusRangeGetWithHttpInfo(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), string? cursor = default(string?), int? limit = default(int?));
        /// <summary>
        /// Get external API transactions by interactionId
        /// </summary>
        /// <remarks>
        /// Get all external API transaction records for the specified interaction.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="interactionId">ID of the interaction to retrieve records for.</param>
        /// <param name="version"></param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <returns>InteractionsExternalApiTransactionDtoGetResponseDto</returns>
        InteractionsExternalApiTransactionDtoGetResponseDto VversionInteractionsInteractionIdTransactionsGet(Guid interactionId, string version, bool? showOnlyFailedTransactions = default(bool?));

        /// <summary>
        /// Get external API transactions by interactionId
        /// </summary>
        /// <remarks>
        /// Get all external API transaction records for the specified interaction.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="interactionId">ID of the interaction to retrieve records for.</param>
        /// <param name="version"></param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <returns>ApiResponse of InteractionsExternalApiTransactionDtoGetResponseDto</returns>
        ApiResponse<InteractionsExternalApiTransactionDtoGetResponseDto> VversionInteractionsInteractionIdTransactionsGetWithHttpInfo(Guid interactionId, string version, bool? showOnlyFailedTransactions = default(bool?));
        /// <summary>
        /// Post interactions data
        /// </summary>
        /// <remarks>
        /// This endpoint is used to post interactions data to the Interactions API that will be published to Pub/Sub.  A maximum of 100 interactions can be submitted per request.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="interactionsDto"> (optional)</param>
        /// <returns>InteractionsBatchResultDto</returns>
        InteractionsBatchResultDto VversionInteractionsPost(string version, InteractionsDto? interactionsDto = default(InteractionsDto?));

        /// <summary>
        /// Post interactions data
        /// </summary>
        /// <remarks>
        /// This endpoint is used to post interactions data to the Interactions API that will be published to Pub/Sub.  A maximum of 100 interactions can be submitted per request.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="interactionsDto"> (optional)</param>
        /// <returns>ApiResponse of InteractionsBatchResultDto</returns>
        ApiResponse<InteractionsBatchResultDto> VversionInteractionsPostWithHttpInfo(string version, InteractionsDto? interactionsDto = default(InteractionsDto?));
        /// <summary>
        /// Get external API transaction logs by date range
        /// </summary>
        /// <remarks>
        /// Get all external API transaction records within the date range specified, for a maximum of up to a 30 day span.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range to show transactions for (inclusive). Must be provided in UTC, and be within 30 days of endDate. (optional)</param>
        /// <param name="endDate">End of date range to show transactions for (inclusive). Defaults to current date/time if not provided. Must be provided in UTC if specified,              and be within 30 days of startDate. (optional)</param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <returns>InteractionsExternalApiTransactionDtoGetResponseDto</returns>
        InteractionsExternalApiTransactionDtoGetResponseDto VversionInteractionsTransactionsGet(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), bool? showOnlyFailedTransactions = default(bool?));

        /// <summary>
        /// Get external API transaction logs by date range
        /// </summary>
        /// <remarks>
        /// Get all external API transaction records within the date range specified, for a maximum of up to a 30 day span.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range to show transactions for (inclusive). Must be provided in UTC, and be within 30 days of endDate. (optional)</param>
        /// <param name="endDate">End of date range to show transactions for (inclusive). Defaults to current date/time if not provided. Must be provided in UTC if specified,              and be within 30 days of startDate. (optional)</param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <returns>ApiResponse of InteractionsExternalApiTransactionDtoGetResponseDto</returns>
        ApiResponse<InteractionsExternalApiTransactionDtoGetResponseDto> VversionInteractionsTransactionsGetWithHttpInfo(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), bool? showOnlyFailedTransactions = default(bool?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IInteractionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Exchange pipeline statuses by correlation or interaction ID
        /// </summary>
        /// <remarks>
        /// Returns Exchange pipeline statuses filtered by either correlationId or interactionId.  Supports cursor-based pagination.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="correlationId">The correlation ID returned from the initial publish response. (optional)</param>
        /// <param name="interactionId">The interaction&#39;s unique identifier (GUID). (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExchangeInteractionStatusDtoCursorPaginatedResponseDto</returns>
        System.Threading.Tasks.Task<ExchangeInteractionStatusDtoCursorPaginatedResponseDto> VversionInteractionsExchangeStatusGetAsync(string version, string? correlationId = default(string?), Guid? interactionId = default(Guid?), string? cursor = default(string?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get Exchange pipeline statuses by correlation or interaction ID
        /// </summary>
        /// <remarks>
        /// Returns Exchange pipeline statuses filtered by either correlationId or interactionId.  Supports cursor-based pagination.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="correlationId">The correlation ID returned from the initial publish response. (optional)</param>
        /// <param name="interactionId">The interaction&#39;s unique identifier (GUID). (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExchangeInteractionStatusDtoCursorPaginatedResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExchangeInteractionStatusDtoCursorPaginatedResponseDto>> VversionInteractionsExchangeStatusGetWithHttpInfoAsync(string version, string? correlationId = default(string?), Guid? interactionId = default(Guid?), string? cursor = default(string?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get Exchange pipeline statuses by date range
        /// </summary>
        /// <remarks>
        /// Returns Exchange pipeline statuses for interactions published within the specified date range.  Supports cursor-based pagination. Maximum date range is 30 days.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range (inclusive, UTC). (optional)</param>
        /// <param name="endDate">End of date range (inclusive, UTC). Defaults to current UTC time. (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExchangeInteractionStatusDtoCursorPaginatedResponseDto</returns>
        System.Threading.Tasks.Task<ExchangeInteractionStatusDtoCursorPaginatedResponseDto> VversionInteractionsExchangeStatusRangeGetAsync(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), string? cursor = default(string?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get Exchange pipeline statuses by date range
        /// </summary>
        /// <remarks>
        /// Returns Exchange pipeline statuses for interactions published within the specified date range.  Supports cursor-based pagination. Maximum date range is 30 days.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range (inclusive, UTC). (optional)</param>
        /// <param name="endDate">End of date range (inclusive, UTC). Defaults to current UTC time. (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExchangeInteractionStatusDtoCursorPaginatedResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExchangeInteractionStatusDtoCursorPaginatedResponseDto>> VversionInteractionsExchangeStatusRangeGetWithHttpInfoAsync(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), string? cursor = default(string?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get external API transactions by interactionId
        /// </summary>
        /// <remarks>
        /// Get all external API transaction records for the specified interaction.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="interactionId">ID of the interaction to retrieve records for.</param>
        /// <param name="version"></param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InteractionsExternalApiTransactionDtoGetResponseDto</returns>
        System.Threading.Tasks.Task<InteractionsExternalApiTransactionDtoGetResponseDto> VversionInteractionsInteractionIdTransactionsGetAsync(Guid interactionId, string version, bool? showOnlyFailedTransactions = default(bool?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get external API transactions by interactionId
        /// </summary>
        /// <remarks>
        /// Get all external API transaction records for the specified interaction.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="interactionId">ID of the interaction to retrieve records for.</param>
        /// <param name="version"></param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InteractionsExternalApiTransactionDtoGetResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<InteractionsExternalApiTransactionDtoGetResponseDto>> VversionInteractionsInteractionIdTransactionsGetWithHttpInfoAsync(Guid interactionId, string version, bool? showOnlyFailedTransactions = default(bool?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Post interactions data
        /// </summary>
        /// <remarks>
        /// This endpoint is used to post interactions data to the Interactions API that will be published to Pub/Sub.  A maximum of 100 interactions can be submitted per request.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="interactionsDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InteractionsBatchResultDto</returns>
        System.Threading.Tasks.Task<InteractionsBatchResultDto> VversionInteractionsPostAsync(string version, InteractionsDto? interactionsDto = default(InteractionsDto?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Post interactions data
        /// </summary>
        /// <remarks>
        /// This endpoint is used to post interactions data to the Interactions API that will be published to Pub/Sub.  A maximum of 100 interactions can be submitted per request.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="interactionsDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InteractionsBatchResultDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<InteractionsBatchResultDto>> VversionInteractionsPostWithHttpInfoAsync(string version, InteractionsDto? interactionsDto = default(InteractionsDto?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get external API transaction logs by date range
        /// </summary>
        /// <remarks>
        /// Get all external API transaction records within the date range specified, for a maximum of up to a 30 day span.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range to show transactions for (inclusive). Must be provided in UTC, and be within 30 days of endDate. (optional)</param>
        /// <param name="endDate">End of date range to show transactions for (inclusive). Defaults to current date/time if not provided. Must be provided in UTC if specified,              and be within 30 days of startDate. (optional)</param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InteractionsExternalApiTransactionDtoGetResponseDto</returns>
        System.Threading.Tasks.Task<InteractionsExternalApiTransactionDtoGetResponseDto> VversionInteractionsTransactionsGetAsync(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), bool? showOnlyFailedTransactions = default(bool?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get external API transaction logs by date range
        /// </summary>
        /// <remarks>
        /// Get all external API transaction records within the date range specified, for a maximum of up to a 30 day span.
        /// </remarks>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range to show transactions for (inclusive). Must be provided in UTC, and be within 30 days of endDate. (optional)</param>
        /// <param name="endDate">End of date range to show transactions for (inclusive). Defaults to current date/time if not provided. Must be provided in UTC if specified,              and be within 30 days of startDate. (optional)</param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InteractionsExternalApiTransactionDtoGetResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<InteractionsExternalApiTransactionDtoGetResponseDto>> VversionInteractionsTransactionsGetWithHttpInfoAsync(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), bool? showOnlyFailedTransactions = default(bool?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IInteractionsApi : IInteractionsApiSync, IInteractionsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class InteractionsApi : IDisposable, IInteractionsApi
    {
        private Ddx.InteractionsApi.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public InteractionsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public InteractionsApi(string basePath)
        {
            this.Configuration = Ddx.InteractionsApi.Client.Configuration.MergeConfigurations(
                Ddx.InteractionsApi.Client.GlobalConfiguration.Instance,
                new Ddx.InteractionsApi.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Ddx.InteractionsApi.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Ddx.InteractionsApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public InteractionsApi(Ddx.InteractionsApi.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Ddx.InteractionsApi.Client.Configuration.MergeConfigurations(
                Ddx.InteractionsApi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Ddx.InteractionsApi.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Ddx.InteractionsApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public InteractionsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public InteractionsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Ddx.InteractionsApi.Client.Configuration.MergeConfigurations(
                Ddx.InteractionsApi.Client.GlobalConfiguration.Instance,
                new Ddx.InteractionsApi.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Ddx.InteractionsApi.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Ddx.InteractionsApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public InteractionsApi(HttpClient client, Ddx.InteractionsApi.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Ddx.InteractionsApi.Client.Configuration.MergeConfigurations(
                Ddx.InteractionsApi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Ddx.InteractionsApi.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Ddx.InteractionsApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InteractionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public InteractionsApi(Ddx.InteractionsApi.Client.ISynchronousClient client, Ddx.InteractionsApi.Client.IAsynchronousClient asyncClient, Ddx.InteractionsApi.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Ddx.InteractionsApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Ddx.InteractionsApi.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Ddx.InteractionsApi.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Ddx.InteractionsApi.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Ddx.InteractionsApi.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Ddx.InteractionsApi.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Exchange pipeline statuses by correlation or interaction ID Returns Exchange pipeline statuses filtered by either correlationId or interactionId.  Supports cursor-based pagination.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="correlationId">The correlation ID returned from the initial publish response. (optional)</param>
        /// <param name="interactionId">The interaction&#39;s unique identifier (GUID). (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <returns>ExchangeInteractionStatusDtoCursorPaginatedResponseDto</returns>
        public ExchangeInteractionStatusDtoCursorPaginatedResponseDto VversionInteractionsExchangeStatusGet(string version, string? correlationId = default(string?), Guid? interactionId = default(Guid?), string? cursor = default(string?), int? limit = default(int?))
        {
            Ddx.InteractionsApi.Client.ApiResponse<ExchangeInteractionStatusDtoCursorPaginatedResponseDto> localVarResponse = VversionInteractionsExchangeStatusGetWithHttpInfo(version, correlationId, interactionId, cursor, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Exchange pipeline statuses by correlation or interaction ID Returns Exchange pipeline statuses filtered by either correlationId or interactionId.  Supports cursor-based pagination.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="correlationId">The correlation ID returned from the initial publish response. (optional)</param>
        /// <param name="interactionId">The interaction&#39;s unique identifier (GUID). (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <returns>ApiResponse of ExchangeInteractionStatusDtoCursorPaginatedResponseDto</returns>
        public Ddx.InteractionsApi.Client.ApiResponse<ExchangeInteractionStatusDtoCursorPaginatedResponseDto> VversionInteractionsExchangeStatusGetWithHttpInfo(string version, string? correlationId = default(string?), Guid? interactionId = default(Guid?), string? cursor = default(string?), int? limit = default(int?))
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new Ddx.InteractionsApi.Client.ApiException(400, "Missing required parameter 'version' when calling InteractionsApi->VversionInteractionsExchangeStatusGet");

            Ddx.InteractionsApi.Client.RequestOptions localVarRequestOptions = new Ddx.InteractionsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("version", Ddx.InteractionsApi.Client.ClientUtils.ParameterToString(version)); // path parameter
            if (correlationId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "correlationId", correlationId));
            }
            if (interactionId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "interactionId", interactionId));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (Basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Ddx.InteractionsApi.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ExchangeInteractionStatusDtoCursorPaginatedResponseDto>("/v{version}/interactions/exchange-status", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VversionInteractionsExchangeStatusGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Exchange pipeline statuses by correlation or interaction ID Returns Exchange pipeline statuses filtered by either correlationId or interactionId.  Supports cursor-based pagination.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="correlationId">The correlation ID returned from the initial publish response. (optional)</param>
        /// <param name="interactionId">The interaction&#39;s unique identifier (GUID). (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExchangeInteractionStatusDtoCursorPaginatedResponseDto</returns>
        public async System.Threading.Tasks.Task<ExchangeInteractionStatusDtoCursorPaginatedResponseDto> VversionInteractionsExchangeStatusGetAsync(string version, string? correlationId = default(string?), Guid? interactionId = default(Guid?), string? cursor = default(string?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Ddx.InteractionsApi.Client.ApiResponse<ExchangeInteractionStatusDtoCursorPaginatedResponseDto> localVarResponse = await VversionInteractionsExchangeStatusGetWithHttpInfoAsync(version, correlationId, interactionId, cursor, limit, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Exchange pipeline statuses by correlation or interaction ID Returns Exchange pipeline statuses filtered by either correlationId or interactionId.  Supports cursor-based pagination.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="correlationId">The correlation ID returned from the initial publish response. (optional)</param>
        /// <param name="interactionId">The interaction&#39;s unique identifier (GUID). (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExchangeInteractionStatusDtoCursorPaginatedResponseDto)</returns>
        public async System.Threading.Tasks.Task<Ddx.InteractionsApi.Client.ApiResponse<ExchangeInteractionStatusDtoCursorPaginatedResponseDto>> VversionInteractionsExchangeStatusGetWithHttpInfoAsync(string version, string? correlationId = default(string?), Guid? interactionId = default(Guid?), string? cursor = default(string?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new Ddx.InteractionsApi.Client.ApiException(400, "Missing required parameter 'version' when calling InteractionsApi->VversionInteractionsExchangeStatusGet");


            Ddx.InteractionsApi.Client.RequestOptions localVarRequestOptions = new Ddx.InteractionsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("version", Ddx.InteractionsApi.Client.ClientUtils.ParameterToString(version)); // path parameter
            if (correlationId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "correlationId", correlationId));
            }
            if (interactionId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "interactionId", interactionId));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (Basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Ddx.InteractionsApi.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ExchangeInteractionStatusDtoCursorPaginatedResponseDto>("/v{version}/interactions/exchange-status", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VversionInteractionsExchangeStatusGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Exchange pipeline statuses by date range Returns Exchange pipeline statuses for interactions published within the specified date range.  Supports cursor-based pagination. Maximum date range is 30 days.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range (inclusive, UTC). (optional)</param>
        /// <param name="endDate">End of date range (inclusive, UTC). Defaults to current UTC time. (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <returns>ExchangeInteractionStatusDtoCursorPaginatedResponseDto</returns>
        public ExchangeInteractionStatusDtoCursorPaginatedResponseDto VversionInteractionsExchangeStatusRangeGet(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), string? cursor = default(string?), int? limit = default(int?))
        {
            Ddx.InteractionsApi.Client.ApiResponse<ExchangeInteractionStatusDtoCursorPaginatedResponseDto> localVarResponse = VversionInteractionsExchangeStatusRangeGetWithHttpInfo(version, startDate, endDate, cursor, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Exchange pipeline statuses by date range Returns Exchange pipeline statuses for interactions published within the specified date range.  Supports cursor-based pagination. Maximum date range is 30 days.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range (inclusive, UTC). (optional)</param>
        /// <param name="endDate">End of date range (inclusive, UTC). Defaults to current UTC time. (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <returns>ApiResponse of ExchangeInteractionStatusDtoCursorPaginatedResponseDto</returns>
        public Ddx.InteractionsApi.Client.ApiResponse<ExchangeInteractionStatusDtoCursorPaginatedResponseDto> VversionInteractionsExchangeStatusRangeGetWithHttpInfo(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), string? cursor = default(string?), int? limit = default(int?))
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new Ddx.InteractionsApi.Client.ApiException(400, "Missing required parameter 'version' when calling InteractionsApi->VversionInteractionsExchangeStatusRangeGet");

            Ddx.InteractionsApi.Client.RequestOptions localVarRequestOptions = new Ddx.InteractionsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("version", Ddx.InteractionsApi.Client.ClientUtils.ParameterToString(version)); // path parameter
            if (startDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "startDate", startDate));
            }
            if (endDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "endDate", endDate));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (Basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Ddx.InteractionsApi.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ExchangeInteractionStatusDtoCursorPaginatedResponseDto>("/v{version}/interactions/exchange-status/range", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VversionInteractionsExchangeStatusRangeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Exchange pipeline statuses by date range Returns Exchange pipeline statuses for interactions published within the specified date range.  Supports cursor-based pagination. Maximum date range is 30 days.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range (inclusive, UTC). (optional)</param>
        /// <param name="endDate">End of date range (inclusive, UTC). Defaults to current UTC time. (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExchangeInteractionStatusDtoCursorPaginatedResponseDto</returns>
        public async System.Threading.Tasks.Task<ExchangeInteractionStatusDtoCursorPaginatedResponseDto> VversionInteractionsExchangeStatusRangeGetAsync(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), string? cursor = default(string?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Ddx.InteractionsApi.Client.ApiResponse<ExchangeInteractionStatusDtoCursorPaginatedResponseDto> localVarResponse = await VversionInteractionsExchangeStatusRangeGetWithHttpInfoAsync(version, startDate, endDate, cursor, limit, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Exchange pipeline statuses by date range Returns Exchange pipeline statuses for interactions published within the specified date range.  Supports cursor-based pagination. Maximum date range is 30 days.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range (inclusive, UTC). (optional)</param>
        /// <param name="endDate">End of date range (inclusive, UTC). Defaults to current UTC time. (optional)</param>
        /// <param name="cursor">Opaque pagination token from a previous response&#39;s nextCursor field. (optional)</param>
        /// <param name="limit">Maximum number of results to return (default 100, max 1000). (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExchangeInteractionStatusDtoCursorPaginatedResponseDto)</returns>
        public async System.Threading.Tasks.Task<Ddx.InteractionsApi.Client.ApiResponse<ExchangeInteractionStatusDtoCursorPaginatedResponseDto>> VversionInteractionsExchangeStatusRangeGetWithHttpInfoAsync(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), string? cursor = default(string?), int? limit = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new Ddx.InteractionsApi.Client.ApiException(400, "Missing required parameter 'version' when calling InteractionsApi->VversionInteractionsExchangeStatusRangeGet");


            Ddx.InteractionsApi.Client.RequestOptions localVarRequestOptions = new Ddx.InteractionsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("version", Ddx.InteractionsApi.Client.ClientUtils.ParameterToString(version)); // path parameter
            if (startDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "startDate", startDate));
            }
            if (endDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "endDate", endDate));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (Basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Ddx.InteractionsApi.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ExchangeInteractionStatusDtoCursorPaginatedResponseDto>("/v{version}/interactions/exchange-status/range", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VversionInteractionsExchangeStatusRangeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get external API transactions by interactionId Get all external API transaction records for the specified interaction.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="interactionId">ID of the interaction to retrieve records for.</param>
        /// <param name="version"></param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <returns>InteractionsExternalApiTransactionDtoGetResponseDto</returns>
        public InteractionsExternalApiTransactionDtoGetResponseDto VversionInteractionsInteractionIdTransactionsGet(Guid interactionId, string version, bool? showOnlyFailedTransactions = default(bool?))
        {
            Ddx.InteractionsApi.Client.ApiResponse<InteractionsExternalApiTransactionDtoGetResponseDto> localVarResponse = VversionInteractionsInteractionIdTransactionsGetWithHttpInfo(interactionId, version, showOnlyFailedTransactions);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get external API transactions by interactionId Get all external API transaction records for the specified interaction.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="interactionId">ID of the interaction to retrieve records for.</param>
        /// <param name="version"></param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <returns>ApiResponse of InteractionsExternalApiTransactionDtoGetResponseDto</returns>
        public Ddx.InteractionsApi.Client.ApiResponse<InteractionsExternalApiTransactionDtoGetResponseDto> VversionInteractionsInteractionIdTransactionsGetWithHttpInfo(Guid interactionId, string version, bool? showOnlyFailedTransactions = default(bool?))
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new Ddx.InteractionsApi.Client.ApiException(400, "Missing required parameter 'version' when calling InteractionsApi->VversionInteractionsInteractionIdTransactionsGet");

            Ddx.InteractionsApi.Client.RequestOptions localVarRequestOptions = new Ddx.InteractionsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("interactionId", Ddx.InteractionsApi.Client.ClientUtils.ParameterToString(interactionId)); // path parameter
            localVarRequestOptions.PathParameters.Add("version", Ddx.InteractionsApi.Client.ClientUtils.ParameterToString(version)); // path parameter
            if (showOnlyFailedTransactions != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "showOnlyFailedTransactions", showOnlyFailedTransactions));
            }

            // authentication (Basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Ddx.InteractionsApi.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<InteractionsExternalApiTransactionDtoGetResponseDto>("/v{version}/interactions/{interactionId}/transactions", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VversionInteractionsInteractionIdTransactionsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get external API transactions by interactionId Get all external API transaction records for the specified interaction.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="interactionId">ID of the interaction to retrieve records for.</param>
        /// <param name="version"></param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InteractionsExternalApiTransactionDtoGetResponseDto</returns>
        public async System.Threading.Tasks.Task<InteractionsExternalApiTransactionDtoGetResponseDto> VversionInteractionsInteractionIdTransactionsGetAsync(Guid interactionId, string version, bool? showOnlyFailedTransactions = default(bool?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Ddx.InteractionsApi.Client.ApiResponse<InteractionsExternalApiTransactionDtoGetResponseDto> localVarResponse = await VversionInteractionsInteractionIdTransactionsGetWithHttpInfoAsync(interactionId, version, showOnlyFailedTransactions, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get external API transactions by interactionId Get all external API transaction records for the specified interaction.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="interactionId">ID of the interaction to retrieve records for.</param>
        /// <param name="version"></param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InteractionsExternalApiTransactionDtoGetResponseDto)</returns>
        public async System.Threading.Tasks.Task<Ddx.InteractionsApi.Client.ApiResponse<InteractionsExternalApiTransactionDtoGetResponseDto>> VversionInteractionsInteractionIdTransactionsGetWithHttpInfoAsync(Guid interactionId, string version, bool? showOnlyFailedTransactions = default(bool?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new Ddx.InteractionsApi.Client.ApiException(400, "Missing required parameter 'version' when calling InteractionsApi->VversionInteractionsInteractionIdTransactionsGet");


            Ddx.InteractionsApi.Client.RequestOptions localVarRequestOptions = new Ddx.InteractionsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("interactionId", Ddx.InteractionsApi.Client.ClientUtils.ParameterToString(interactionId)); // path parameter
            localVarRequestOptions.PathParameters.Add("version", Ddx.InteractionsApi.Client.ClientUtils.ParameterToString(version)); // path parameter
            if (showOnlyFailedTransactions != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "showOnlyFailedTransactions", showOnlyFailedTransactions));
            }

            // authentication (Basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Ddx.InteractionsApi.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<InteractionsExternalApiTransactionDtoGetResponseDto>("/v{version}/interactions/{interactionId}/transactions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VversionInteractionsInteractionIdTransactionsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Post interactions data This endpoint is used to post interactions data to the Interactions API that will be published to Pub/Sub.  A maximum of 100 interactions can be submitted per request.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="interactionsDto"> (optional)</param>
        /// <returns>InteractionsBatchResultDto</returns>
        public InteractionsBatchResultDto VversionInteractionsPost(string version, InteractionsDto? interactionsDto = default(InteractionsDto?))
        {
            Ddx.InteractionsApi.Client.ApiResponse<InteractionsBatchResultDto> localVarResponse = VversionInteractionsPostWithHttpInfo(version, interactionsDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Post interactions data This endpoint is used to post interactions data to the Interactions API that will be published to Pub/Sub.  A maximum of 100 interactions can be submitted per request.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="interactionsDto"> (optional)</param>
        /// <returns>ApiResponse of InteractionsBatchResultDto</returns>
        public Ddx.InteractionsApi.Client.ApiResponse<InteractionsBatchResultDto> VversionInteractionsPostWithHttpInfo(string version, InteractionsDto? interactionsDto = default(InteractionsDto?))
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new Ddx.InteractionsApi.Client.ApiException(400, "Missing required parameter 'version' when calling InteractionsApi->VversionInteractionsPost");

            Ddx.InteractionsApi.Client.RequestOptions localVarRequestOptions = new Ddx.InteractionsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("version", Ddx.InteractionsApi.Client.ClientUtils.ParameterToString(version)); // path parameter
            localVarRequestOptions.Data = interactionsDto;

            // authentication (Basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Ddx.InteractionsApi.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<InteractionsBatchResultDto>("/v{version}/interactions", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VversionInteractionsPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Post interactions data This endpoint is used to post interactions data to the Interactions API that will be published to Pub/Sub.  A maximum of 100 interactions can be submitted per request.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="interactionsDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InteractionsBatchResultDto</returns>
        public async System.Threading.Tasks.Task<InteractionsBatchResultDto> VversionInteractionsPostAsync(string version, InteractionsDto? interactionsDto = default(InteractionsDto?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Ddx.InteractionsApi.Client.ApiResponse<InteractionsBatchResultDto> localVarResponse = await VversionInteractionsPostWithHttpInfoAsync(version, interactionsDto, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Post interactions data This endpoint is used to post interactions data to the Interactions API that will be published to Pub/Sub.  A maximum of 100 interactions can be submitted per request.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="interactionsDto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InteractionsBatchResultDto)</returns>
        public async System.Threading.Tasks.Task<Ddx.InteractionsApi.Client.ApiResponse<InteractionsBatchResultDto>> VversionInteractionsPostWithHttpInfoAsync(string version, InteractionsDto? interactionsDto = default(InteractionsDto?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new Ddx.InteractionsApi.Client.ApiException(400, "Missing required parameter 'version' when calling InteractionsApi->VversionInteractionsPost");


            Ddx.InteractionsApi.Client.RequestOptions localVarRequestOptions = new Ddx.InteractionsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("version", Ddx.InteractionsApi.Client.ClientUtils.ParameterToString(version)); // path parameter
            localVarRequestOptions.Data = interactionsDto;

            // authentication (Basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Ddx.InteractionsApi.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<InteractionsBatchResultDto>("/v{version}/interactions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VversionInteractionsPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get external API transaction logs by date range Get all external API transaction records within the date range specified, for a maximum of up to a 30 day span.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range to show transactions for (inclusive). Must be provided in UTC, and be within 30 days of endDate. (optional)</param>
        /// <param name="endDate">End of date range to show transactions for (inclusive). Defaults to current date/time if not provided. Must be provided in UTC if specified,              and be within 30 days of startDate. (optional)</param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <returns>InteractionsExternalApiTransactionDtoGetResponseDto</returns>
        public InteractionsExternalApiTransactionDtoGetResponseDto VversionInteractionsTransactionsGet(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), bool? showOnlyFailedTransactions = default(bool?))
        {
            Ddx.InteractionsApi.Client.ApiResponse<InteractionsExternalApiTransactionDtoGetResponseDto> localVarResponse = VversionInteractionsTransactionsGetWithHttpInfo(version, startDate, endDate, showOnlyFailedTransactions);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get external API transaction logs by date range Get all external API transaction records within the date range specified, for a maximum of up to a 30 day span.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range to show transactions for (inclusive). Must be provided in UTC, and be within 30 days of endDate. (optional)</param>
        /// <param name="endDate">End of date range to show transactions for (inclusive). Defaults to current date/time if not provided. Must be provided in UTC if specified,              and be within 30 days of startDate. (optional)</param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <returns>ApiResponse of InteractionsExternalApiTransactionDtoGetResponseDto</returns>
        public Ddx.InteractionsApi.Client.ApiResponse<InteractionsExternalApiTransactionDtoGetResponseDto> VversionInteractionsTransactionsGetWithHttpInfo(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), bool? showOnlyFailedTransactions = default(bool?))
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new Ddx.InteractionsApi.Client.ApiException(400, "Missing required parameter 'version' when calling InteractionsApi->VversionInteractionsTransactionsGet");

            Ddx.InteractionsApi.Client.RequestOptions localVarRequestOptions = new Ddx.InteractionsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("version", Ddx.InteractionsApi.Client.ClientUtils.ParameterToString(version)); // path parameter
            if (startDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "startDate", startDate));
            }
            if (endDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "endDate", endDate));
            }
            if (showOnlyFailedTransactions != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "showOnlyFailedTransactions", showOnlyFailedTransactions));
            }

            // authentication (Basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Ddx.InteractionsApi.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<InteractionsExternalApiTransactionDtoGetResponseDto>("/v{version}/interactions/transactions", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VversionInteractionsTransactionsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get external API transaction logs by date range Get all external API transaction records within the date range specified, for a maximum of up to a 30 day span.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range to show transactions for (inclusive). Must be provided in UTC, and be within 30 days of endDate. (optional)</param>
        /// <param name="endDate">End of date range to show transactions for (inclusive). Defaults to current date/time if not provided. Must be provided in UTC if specified,              and be within 30 days of startDate. (optional)</param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InteractionsExternalApiTransactionDtoGetResponseDto</returns>
        public async System.Threading.Tasks.Task<InteractionsExternalApiTransactionDtoGetResponseDto> VversionInteractionsTransactionsGetAsync(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), bool? showOnlyFailedTransactions = default(bool?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Ddx.InteractionsApi.Client.ApiResponse<InteractionsExternalApiTransactionDtoGetResponseDto> localVarResponse = await VversionInteractionsTransactionsGetWithHttpInfoAsync(version, startDate, endDate, showOnlyFailedTransactions, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get external API transaction logs by date range Get all external API transaction records within the date range specified, for a maximum of up to a 30 day span.
        /// </summary>
        /// <exception cref="Ddx.InteractionsApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="version"></param>
        /// <param name="startDate">Beginning of date range to show transactions for (inclusive). Must be provided in UTC, and be within 30 days of endDate. (optional)</param>
        /// <param name="endDate">End of date range to show transactions for (inclusive). Defaults to current date/time if not provided. Must be provided in UTC if specified,              and be within 30 days of startDate. (optional)</param>
        /// <param name="showOnlyFailedTransactions">When true, will return only transactions with Failed, Invalid, or Duplicate status. True by default. (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InteractionsExternalApiTransactionDtoGetResponseDto)</returns>
        public async System.Threading.Tasks.Task<Ddx.InteractionsApi.Client.ApiResponse<InteractionsExternalApiTransactionDtoGetResponseDto>> VversionInteractionsTransactionsGetWithHttpInfoAsync(string version, DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), bool? showOnlyFailedTransactions = default(bool?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'version' is set
            if (version == null)
                throw new Ddx.InteractionsApi.Client.ApiException(400, "Missing required parameter 'version' when calling InteractionsApi->VversionInteractionsTransactionsGet");


            Ddx.InteractionsApi.Client.RequestOptions localVarRequestOptions = new Ddx.InteractionsApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Ddx.InteractionsApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("version", Ddx.InteractionsApi.Client.ClientUtils.ParameterToString(version)); // path parameter
            if (startDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "startDate", startDate));
            }
            if (endDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "endDate", endDate));
            }
            if (showOnlyFailedTransactions != null)
            {
                localVarRequestOptions.QueryParameters.Add(Ddx.InteractionsApi.Client.ClientUtils.ParameterToMultiMap("", "showOnlyFailedTransactions", showOnlyFailedTransactions));
            }

            // authentication (Basic) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Ddx.InteractionsApi.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<InteractionsExternalApiTransactionDtoGetResponseDto>("/v{version}/interactions/transactions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VversionInteractionsTransactionsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
