# coding: utf-8

"""
    Interactions API

    Interactions API documentation

    The version of the OpenAPI document: v1
    Contact: api@demexchange.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CommunicationConsentStatus(str, Enum):
    """
    CommunicationConsentStatus
    """

    """
    allowed enum values
    """
    OPTED_IN = 'opted_in'
    OPTED_OUT = 'opted_out'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CommunicationConsentStatus from a JSON string"""
        return cls(json.loads(json_str))


