# coding: utf-8

"""
    Interactions API

    Interactions API documentation

    The version of the OpenAPI document: v1
    Contact: api@demexchange.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from mig_interactions_api.models.address import Address
from typing import Optional, Set
from typing_extensions import Self

class ContactInfo(BaseModel):
    """
    Represents contact information for a person being interacted with, including email, phone, or address.  Can be used to match a person if an Id is not known
    """ # noqa: E501
    email: Optional[List[StrictStr]] = Field(default=None, description="Email addresses of the person being interacted with.")
    phone: Optional[List[StrictStr]] = Field(default=None, description="Phone numbers of the person being interacted with. Should be in E.164 format (e.g. +1234567890).")
    address: Optional[List[Address]] = Field(default=None, description="Physical addresses of the person being interacted with.")
    first_name: Optional[StrictStr] = Field(default=None, description="Optional first name field for person being interacted with.", alias="firstName")
    middle_name: Optional[StrictStr] = Field(default=None, description="Optional middle name field for person being interacted with.", alias="middleName")
    last_name: Optional[StrictStr] = Field(default=None, description="Optional last name field for person being interacted with.", alias="lastName")
    social_handle: Optional[List[StrictStr]] = Field(default=None, description="Optional social media handles for person being interacted with.", alias="socialHandle")
    __properties: ClassVar[List[str]] = ["email", "phone", "address", "firstName", "middleName", "lastName", "socialHandle"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContactInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in address (list)
        _items = []
        if self.address:
            for _item_address in self.address:
                if _item_address:
                    _items.append(_item_address.to_dict())
            _dict['address'] = _items
        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if first_name (nullable) is None
        # and model_fields_set contains the field
        if self.first_name is None and "first_name" in self.model_fields_set:
            _dict['firstName'] = None

        # set to None if middle_name (nullable) is None
        # and model_fields_set contains the field
        if self.middle_name is None and "middle_name" in self.model_fields_set:
            _dict['middleName'] = None

        # set to None if last_name (nullable) is None
        # and model_fields_set contains the field
        if self.last_name is None and "last_name" in self.model_fields_set:
            _dict['lastName'] = None

        # set to None if social_handle (nullable) is None
        # and model_fields_set contains the field
        if self.social_handle is None and "social_handle" in self.model_fields_set:
            _dict['socialHandle'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContactInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "email": obj.get("email"),
            "phone": obj.get("phone"),
            "address": [Address.from_dict(_item) for _item in obj["address"]] if obj.get("address") is not None else None,
            "firstName": obj.get("firstName"),
            "middleName": obj.get("middleName"),
            "lastName": obj.get("lastName"),
            "socialHandle": obj.get("socialHandle")
        })
        return _obj


