# coding: utf-8

"""
    Interactions API

    Interactions API documentation

    The version of the OpenAPI document: v1
    Contact: api@demexchange.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from mig_interactions_api.models.event_details import EventDetails
from mig_interactions_api.models.event_role import EventRole
from mig_interactions_api.models.event_signup_status import EventSignupStatus
from typing import Optional, Set
from typing_extensions import Self

class EventSignup(BaseModel):
    """
    Represents an event signup captured during an interaction.
    """ # noqa: E501
    event_id: EventDetails
    shifts: Optional[List[EventDetails]] = Field(default=None, description="Optional array of shift identifiers for specific shifts within the event")
    role: Optional[EventRole] = None
    status: Optional[EventSignupStatus] = None
    __properties: ClassVar[List[str]] = ["event_id", "shifts", "role", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EventSignup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of event_id
        if self.event_id:
            _dict['event_id'] = self.event_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in shifts (list)
        _items = []
        if self.shifts:
            for _item_shifts in self.shifts:
                if _item_shifts:
                    _items.append(_item_shifts.to_dict())
            _dict['shifts'] = _items
        # override the default output from pydantic by calling `to_dict()` of role
        if self.role:
            _dict['role'] = self.role.to_dict()
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        # set to None if shifts (nullable) is None
        # and model_fields_set contains the field
        if self.shifts is None and "shifts" in self.model_fields_set:
            _dict['shifts'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EventSignup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_id": EventDetails.from_dict(obj["event_id"]) if obj.get("event_id") is not None else None,
            "shifts": [EventDetails.from_dict(_item) for _item in obj["shifts"]] if obj.get("shifts") is not None else None,
            "role": EventRole.from_dict(obj["role"]) if obj.get("role") is not None else None,
            "status": EventSignupStatus.from_dict(obj["status"]) if obj.get("status") is not None else None
        })
        return _obj


