# coding: utf-8

"""
    Interactions API

    Interactions API documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EventSignupStatusValue(str, Enum):
    """
    Valid event signup status values
    """

    """
    allowed enum values
    """
    SCHEDULED = 'scheduled'
    WAITLISTED = 'waitlisted'
    INVITED = 'invited'
    COMPLETED = 'completed'
    CONFIRMED = 'confirmed'
    CANCELLED = 'cancelled'
    NO_SHOW = 'no_show'
    PARTIAL = 'partial'
    CANNOT_ATTEND = 'cannot_attend'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EventSignupStatusValue from a JSON string"""
        return cls(json.loads(json_str))


