# coding: utf-8

"""
    Interactions API

    Interactions API documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ExchangeInteractionStatus(str, Enum):
    """
    Status of an interaction's progress through the Exchange data pipeline.
    """

    """
    allowed enum values
    """
    QUEUED = 'Queued'
    PROCESSED = 'Processed'
    PARTIALLYORFULLYUNSUPPORTED = 'PartiallyOrFullyUnsupported'
    ERROR = 'Error'
    UNKNOWN = 'Unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExchangeInteractionStatus from a JSON string"""
        return cls(json.loads(json_str))


