# coding: utf-8

"""
    Interactions API

    Interactions API documentation

    The version of the OpenAPI document: v1
    Contact: api@demexchange.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from mig_interactions_api.models.exchange_interaction_status import ExchangeInteractionStatus
from typing import Optional, Set
from typing_extensions import Self

class ExchangeInteractionStatusDto(BaseModel):
    """
    Per-interaction status through the Exchange data pipeline.
    """ # noqa: E501
    correlation_id: Optional[StrictStr] = Field(default=None, description="DDx API request identifier.", alias="correlationId")
    interaction_id: Optional[StrictStr] = Field(default=None, description="The interaction's unique identifier.", alias="interactionId")
    status: Optional[ExchangeInteractionStatus] = None
    exchange_data_types: Optional[StrictStr] = Field(default=None, description="The Exchange data types the interaction was transformed into.", alias="exchangeDataTypes")
    publish_time: Optional[datetime] = Field(default=None, description="Timestamp when the interaction was received into the Exchange pipeline (Pub/Sub publish time).", alias="publishTime")
    __properties: ClassVar[List[str]] = ["correlationId", "interactionId", "status", "exchangeDataTypes", "publishTime"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExchangeInteractionStatusDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if interaction_id (nullable) is None
        # and model_fields_set contains the field
        if self.interaction_id is None and "interaction_id" in self.model_fields_set:
            _dict['interactionId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExchangeInteractionStatusDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "correlationId": obj.get("correlationId"),
            "interactionId": obj.get("interactionId"),
            "status": obj.get("status"),
            "exchangeDataTypes": obj.get("exchangeDataTypes"),
            "publishTime": obj.get("publishTime")
        })
        return _obj


