=begin
#Interactions API

#Interactions API documentation

The version of the OpenAPI document: v1
Contact: api@demexchange.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

# Common files
require 'ddx_interactions_api/api_client'
require 'ddx_interactions_api/api_error'
require 'ddx_interactions_api/version'
require 'ddx_interactions_api/configuration'

# Models
require 'ddx_interactions_api/models/accepted_interaction_dto'
require 'ddx_interactions_api/models/accepted_interactions_dto'
require 'ddx_interactions_api/models/activist_code'
require 'ddx_interactions_api/models/activist_code_outcome_details'
require 'ddx_interactions_api/models/address'
require 'ddx_interactions_api/models/address_channel_details'
require 'ddx_interactions_api/models/canvasser_details'
require 'ddx_interactions_api/models/committee_details'
require 'ddx_interactions_api/models/communication_consent'
require 'ddx_interactions_api/models/communication_consent_outcome_details'
require 'ddx_interactions_api/models/communication_consent_status'
require 'ddx_interactions_api/models/contact_info'
require 'ddx_interactions_api/models/contact_method'
require 'ddx_interactions_api/models/dynamic_channel_details'
require 'ddx_interactions_api/models/dynamic_outcome_details'
require 'ddx_interactions_api/models/event_details'
require 'ddx_interactions_api/models/event_role'
require 'ddx_interactions_api/models/event_signup'
require 'ddx_interactions_api/models/event_signup_outcome_details'
require 'ddx_interactions_api/models/event_signup_status'
require 'ddx_interactions_api/models/event_signup_status_value'
require 'ddx_interactions_api/models/exchange_interaction_status'
require 'ddx_interactions_api/models/exchange_interaction_status_dto'
require 'ddx_interactions_api/models/exchange_interaction_status_dto_cursor_paginated_response_dto'
require 'ddx_interactions_api/models/external_api_key_status'
require 'ddx_interactions_api/models/external_api_key_type'
require 'ddx_interactions_api/models/external_transaction_status'
require 'ddx_interactions_api/models/initiative_dto'
require 'ddx_interactions_api/models/interaction_dto'
require 'ddx_interactions_api/models/interaction_dto_channel'
require 'ddx_interactions_api/models/interaction_dto_outcomes_detailed_inner'
require 'ddx_interactions_api/models/interaction_error_dto'
require 'ddx_interactions_api/models/interaction_van_fields_dto'
require 'ddx_interactions_api/models/interactions_batch_result_dto'
require 'ddx_interactions_api/models/interactions_dto'
require 'ddx_interactions_api/models/interactions_external_api_transaction_dto'
require 'ddx_interactions_api/models/interactions_external_api_transaction_dto_get_response_dto'
require 'ddx_interactions_api/models/interactions_external_api_transaction_log_dto'
require 'ddx_interactions_api/models/mercury_destination_van_api_key_dto'
require 'ddx_interactions_api/models/minerva_metadata_dto'
require 'ddx_interactions_api/models/outcome'
require 'ddx_interactions_api/models/outcome_detail_operation'
require 'ddx_interactions_api/models/person_identifier'
require 'ddx_interactions_api/models/rejected_interaction_dto'
require 'ddx_interactions_api/models/rejected_interactions_dto'
require 'ddx_interactions_api/models/simple_destination_dto'
require 'ddx_interactions_api/models/simple_movement_app_dto'
require 'ddx_interactions_api/models/simple_workspace_dto'
require 'ddx_interactions_api/models/survey_response'
require 'ddx_interactions_api/models/survey_response_outcome_details'
require 'ddx_interactions_api/models/van_api_key_dto'
require 'ddx_interactions_api/models/van_database_mode'
require 'ddx_interactions_api/models/who_am_i_api_key_dto'
require 'ddx_interactions_api/models/workspace_type_dto'

# APIs
require 'ddx_interactions_api/api/authentication_details_api'
require 'ddx_interactions_api/api/interactions_api'

module DdxInteractionsApi
  class << self
    # Customize default settings for the SDK using block.
    #   DdxInteractionsApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
