# coding: utf-8

"""
    Interactions API

    Interactions API documentation

    The version of the OpenAPI document: v1
    Contact: api@demexchange.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "ddx-interactions-api"
VERSION = "0.2.0"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
    "certifi >= 2024.2.2",
]

setup(
    name=NAME,
    version=VERSION,
    description="Interactions API",
    author="DDx API Team",
    author_email="api@demexchange.com",
    url="https://github.com/Movement-Infrastructure/interactions-api-sdks",
    keywords=["OpenAPI", "OpenAPI-Generator", "Interactions API"],
    python_requires=PYTHON_REQUIRES,
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT",
    long_description_content_type='text/markdown',
    long_description="""\
    Interactions API documentation
    """,  # noqa: E501
    package_data={"ddx_interactions_api": ["py.typed"]},
)
